# Generated by Django 5.1.7 on 2025-06-24 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'main', 'work', 'anon'",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("undisclosed", "Prefer not to disclose"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("anonymous", "Anonymous"),
                            ("professional", "Professional"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_org_owner", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_private_profile", models.BooleanField(default=False)),
                (
                    "profile_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Customize visibility for profile fields",
                    ),
                ),
                ("experience", models.JSONField(blank=True, default=list, null=True)),
                ("education", models.JSONField(blank=True, default=list, null=True)),
                ("skills", models.JSONField(blank=True, default=list, null=True)),
                (
                    "certifications",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("projects", models.JSONField(blank=True, default=list, null=True)),
                ("languages", models.JSONField(blank=True, default=list, null=True)),
                ("publications", models.JSONField(blank=True, default=list, null=True)),
                ("references", models.JSONField(blank=True, default=list, null=True)),
                (
                    "professional_tab_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The front-end order of professional profile categories",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True, related_name="followed_by", to="user.baseuser"
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="following_by", to="user.baseuser"
                    ),
                ),
            ],
            options={
                "ordering": ["date_joined"],
            },
        ),
        migrations.AddField(
            model_name="authuser",
            name="active_handle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="user.baseuser",
            ),
        ),
    ]
