# Generated by Django 5.1.7 on 2025-06-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_baseuser_certifications_baseuser_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="professional_tab_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="The front-end order of professional profile categories",
            ),
        ),
    ]
