# Generated by Django 5.1.7 on 2025-06-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(choices=[("display", "Display")], max_length=32),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="user.baseuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category", "key")},
            },
        ),
    ]
