# Generated by Django 5.1.7 on 2025-07-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="is_private",
        ),
        migrations.AddField(
            model_name="collection",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("followers", "Followers"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("followers", "Followers"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=20,
            ),
        ),
    ]
