// widgetRegistry.js - COMPLETE WIDGET LIBRARY - ALL 234 WIDGETS FINAL
// Copy this file to: src/features/space/components/widget/widgetRegistry.js

import {
  FaBook, FaCamera, FaTasks, FaCalendar, FaStickyNote, FaLink,
  FaChartLine, FaHeart, FaDumbbell, FaUtensils, FaGlassMartini,
  FaBriefcase, FaGraduationCap, FaHome, FaPlane, FaBaby,
  FaGamepad, FaMusic, FaPalette, FaCoffee, FaDollarSign,
  FaCalculator, FaBullseye, FaClock, FaBookmark, FaUsers,
  FaFolder, FaFileAlt, FaListUl, FaCheckSquare, FaFlask,
  FaAtom, FaRuler, FaChartBar, FaCode, FaDatabase, FaCloud,
  FaCog, FaRobot, FaLightbulb, FaPencilRuler, FaCube,
  FaProjectDiagram, FaMicrochip, FaNetworkWired, FaServer,
  FaTerminal, FaChartPie, FaTable, FaFileCode, FaGitAlt,
  FaRegClipboard, FaSitemap, FaBrain, FaLayerGroup, FaVial,
  FaMicroscope, FaWaveSquare, FaInfinity, FaSquareRootAlt,
  FaPercentage, FaHashtag, FaDraftingCompass, FaTools,
  FaCogs, FaWrench, FaHammer, FaPaintBrush, FaVideo,
  FaEnvelope, FaComments, FaPhoneAlt, FaBell, FaNewspaper,
  FaRss, FaPodcast, FaFilm, FaTv, FaShoppingCart,
  FaReceipt, FaMoneyBillWave, FaPiggyBank, FaCreditCard,
  FaChartArea, FaBalanceScale, FaFileInvoice, FaStar,
  FaArchive, FaTrash, FaEdit, FaEye, FaFilter,
  FaSort, FaSearch, FaUpload, FaDownload, FaShare,
  FaUserTie, FaHandshake, FaBuilding, FaIndustry, FaTruck,
  FaShip, FaWarehouse, FaBoxes, FaClipboardList, FaFileContract,
  FaGavel, FaShieldAlt, FaUserMd, FaHospital, FaNotesMedical,
  FaBullhorn, FaAd, FaUserFriends, FaHeadset,
  FaPoll, FaVoteYea, FaClipboardCheck, FaCertificate, FaMedal,
  FaKey, FaLock, FaFingerprint, FaIdCard, FaPassport,
  FaMapMarkedAlt, FaMapPin, FaRoute, FaRoad, FaCompass,
  FaBitcoin, FaUndo, FaWpforms, FaAddressBook, FaPills,
  FaSyringe, FaHeartbeat, FaXRay, FaDna, FaWeight,
  FaRulerVertical, FaBed, FaWalking, FaRunning, FaBicycle,
  FaSwimmer, FaMountain, FaFileImage, FaFilePdf, FaFileWord,
  FaFileExcel, FaFilePowerpoint, FaFileArchive, FaCarrot,
  FaAppleAlt, FaPizzaSlice, FaWineGlass, FaGlobeAmericas,
  FaDice, FaChess, FaPuzzlePiece, FaTheaterMasks, FaBolt, FaWind
} from 'react-icons/fa';

export const WIDGET_CATEGORIES = [
  { id: 'all', name: 'All Widgets', icon: FaFolder },
  { id: 'productivity', name: 'Productivity', icon: FaTasks },
  { id: 'finance-trading', name: 'Finance & Trading', icon: FaChartLine },
  { id: 'enterprise', name: 'Enterprise & Business', icon: FaBuilding },
  { id: 'supply-chain', name: 'Supply Chain & Ops', icon: FaTruck },
  { id: 'marketing-sales', name: 'Marketing & Sales', icon: FaBullhorn },
  { id: 'hr-team', name: 'HR & Team Management', icon: FaUserFriends },
  { id: 'legal-compliance', name: 'Legal & Compliance', icon: FaGavel },
  { id: 'real-estate', name: 'Real Estate', icon: FaBuilding },
  { id: 'healthcare', name: 'Healthcare', icon: FaHospital },
  { id: 'manufacturing', name: 'Manufacturing', icon: FaIndustry },
  { id: 'science-math', name: 'Science & Math', icon: FaFlask },
  { id: 'engineering', name: 'Engineering', icon: FaCogs },
  { id: 'developer-tools', name: 'Developer Tools', icon: FaCode },
  { id: 'data-analysis', name: 'Data & Analytics', icon: FaChartBar },
  { id: 'research', name: 'Research', icon: FaMicroscope },
  { id: 'design-creative', name: 'Design & Creative', icon: FaPalette },
  { id: 'communication', name: 'Communication', icon: FaComments },
  { id: 'personal-life', name: 'Personal Life', icon: FaHeart },
  { id: 'health-fitness', name: 'Health & Fitness', icon: FaDumbbell },
  { id: 'learning', name: 'Learning', icon: FaGraduationCap },
  { id: 'utilities', name: 'Utilities', icon: FaCalculator }
];

export const WIDGET_REGISTRY = [
  // PRODUCTIVITY (12)
  { id: 'tasks', name: 'Advanced Task Manager', icon: FaTasks, category: 'productivity', description: 'Kanban, Gantt, dependencies', size: 'large', tags: ['tasks', 'kanban'], features: ['Kanban/List/Gantt views', 'Dependencies', 'Time tracking', 'Priority matrix', 'Subtasks', 'Collaboration'] },
  { id: 'notes', name: 'Smart Notes', icon: FaStickyNote, category: 'productivity', description: 'Rich notes with bidirectional links', size: 'large', tags: ['notes', 'pkm'], features: ['Rich text + Markdown', 'Bidirectional links', 'Graph view', 'Tags & folders', 'Templates', 'Search'] },
  { id: 'calendar', name: 'Smart Calendar', icon: FaCalendar, category: 'productivity', description: 'Calendar with time blocking', size: 'large', tags: ['calendar', 'scheduling'], features: ['Month/week/day views', 'Time blocking', 'Smart scheduling', 'Recurring events', 'Reminders', 'Sync'] },
  { id: 'pomodoro', name: 'Focus Timer', icon: FaClock, category: 'productivity', description: 'Pomodoro with analytics', size: 'medium', tags: ['focus', 'pomodoro'], features: ['Pomodoro technique', 'Custom intervals', 'Analytics', 'Distraction log', 'White noise', 'Breaks'] },
  { id: 'mind-map', name: 'Mind Mapper', icon: FaSitemap, category: 'productivity', description: 'Visual brainstorming', size: 'large', tags: ['mind-map'], features: ['Infinite canvas', 'Connections', 'Colors & icons', 'Export', 'Collaboration'] },
  { id: 'project-planner', name: 'Project Planner', icon: FaProjectDiagram, category: 'productivity', description: 'Project planning', size: 'large', tags: ['projects'], features: ['Roadmaps', 'Milestones', 'Resources', 'Budget', 'Risk', 'Reports'] },
  { id: 'meeting-notes', name: 'Meeting Notes', icon: FaUsers, category: 'productivity', description: 'Meeting notes', size: 'medium', tags: ['meetings'], features: ['Templates', 'Action items', 'Attendees', 'Decisions', 'Share'] },
  { id: 'daily-planner', name: 'Daily Planner', icon: FaCalendar, category: 'productivity', description: 'Daily planning', size: 'medium', tags: ['planning'], features: ['Schedule', 'Priorities', 'Time blocks', 'Routine', 'Review'] },
  { id: 'goals', name: 'Goal Tracker', icon: FaBullseye, category: 'productivity', description: 'SMART goals', size: 'medium', tags: ['goals'], features: ['SMART goals', 'Milestones', 'Progress', 'Visual bars', 'Alerts'] },
  { id: 'inbox-zero', name: 'Inbox Zero', icon: FaEnvelope, category: 'productivity', description: 'Email management', size: 'large', tags: ['email'], features: ['Triage', 'Filters', 'Templates', 'Snooze', 'Follow-ups'] },
  { id: 'bookmarks', name: 'Bookmark Manager', icon: FaBookmark, category: 'productivity', description: 'Organize bookmarks', size: 'medium', tags: ['bookmarks'], features: ['Tags', 'Collections', 'Search', 'Import/export', 'Preview'] },
  { id: 'quick-capture', name: 'Quick Capture', icon: FaLightbulb, category: 'productivity', description: 'Capture ideas', size: 'small', tags: ['ideas'], features: ['Quick input', 'Voice notes', 'Tags', 'Process later', 'Sync'] },

  // FINANCE & TRADING (20)
  { id: 'trading-terminal', name: 'Trading Terminal', icon: FaChartLine, category: 'finance-trading', description: 'Trading platform', size: 'large', tags: ['trading'], features: ['Real-time charts', 'Order execution', 'Indicators', 'Multi-asset', 'Portfolio', 'Risk tools'] },
  { id: 'market-scanner', name: 'Market Scanner', icon: FaSearch, category: 'finance-trading', description: 'Market screening', size: 'large', tags: ['scanner'], features: ['Custom filters', 'Patterns', 'Screeners', 'Fundamentals', 'Alerts', 'Watchlists'] },
  { id: 'portfolio-manager', name: 'Portfolio Manager', icon: FaChartPie, category: 'finance-trading', description: 'Track investments', size: 'large', tags: ['portfolio'], features: ['Multi-account', 'Analytics', 'Allocation', 'Dividends', 'Tax lots', 'Rebalancing'] },
  { id: 'quant-analyzer', name: 'Quant Analyzer', icon: FaCalculator, category: 'finance-trading', description: 'Backtesting', size: 'large', tags: ['quant'], features: ['Backtesting', 'Statistics', 'Risk metrics', 'Monte Carlo', 'Factors', 'Indicators'] },
  { id: 'options-analyzer', name: 'Options Analyzer', icon: FaChartArea, category: 'finance-trading', description: 'Options trading', size: 'large', tags: ['options'], features: ['P/L diagrams', 'Greeks', 'Strategies', 'Volatility', 'Probability', 'Chains'] },
  { id: 'crypto-tracker', name: 'Crypto Tracker', icon: FaBitcoin, category: 'finance-trading', description: 'Crypto & DeFi', size: 'large', tags: ['crypto'], features: ['Multi-wallet', 'DeFi', 'NFT', 'Staking', 'Gas', 'Exchange sync'] },
  { id: 'forex-trader', name: 'Forex Trader', icon: FaDollarSign, category: 'finance-trading', description: 'FX trading', size: 'large', tags: ['forex'], features: ['Currency pairs', 'Pip calc', 'Position sizing', 'Calendar', 'Correlation', 'Charts'] },
  { id: 'risk-calc', name: 'Risk Calculator', icon: FaBalanceScale, category: 'finance-trading', description: 'Risk management', size: 'small', tags: ['risk'], features: ['Position sizing', 'Risk/reward', 'Portfolio heat', 'Correlation', 'Kelly'] },
  { id: 'fin-modeling', name: 'Financial Modeling', icon: FaTable, category: 'finance-trading', description: 'Build models', size: 'large', tags: ['modeling'], features: ['DCF models', 'Comps', 'LBO', 'Sensitivity', 'Scenarios', 'Templates'] },
  { id: 'budget-pro', name: 'Budget Manager', icon: FaDollarSign, category: 'finance-trading', description: 'Budgeting', size: 'large', tags: ['budget'], features: ['Multi-department', 'Variance', 'Forecasts', 'What-if', 'Approvals', 'GL'] },
  { id: 'expenses', name: 'Expense Manager', icon: FaReceipt, category: 'finance-trading', description: 'Expense tracking', size: 'medium', tags: ['expenses'], features: ['Receipt scan', 'Approvals', 'Compliance', 'Mileage', 'Cards', 'Export'] },
  { id: 'invoicing', name: 'Invoice & Accounting', icon: FaFileInvoice, category: 'finance-trading', description: 'Invoicing', size: 'large', tags: ['invoicing'], features: ['Invoice gen', 'Payments', 'AR/AP', 'Reconciliation', 'Statements', 'Multi-currency'] },
  { id: 'tax-planner', name: 'Tax Planner', icon: FaCalculator, category: 'finance-trading', description: 'Tax planning', size: 'medium', tags: ['tax'], features: ['Estimation', 'Deductions', 'Tax loss', 'Quarterly', 'Forms', 'Multi-jurisdiction'] },
  { id: 'cashflow', name: 'Cash Flow', icon: FaMoneyBillWave, category: 'finance-trading', description: 'Cash forecasting', size: 'large', tags: ['cashflow'], features: ['Projections', 'Scenarios', 'Burn rate', 'Runway', 'Working capital'] },
  { id: 'payroll', name: 'Payroll', icon: FaMoneyBillWave, category: 'finance-trading', description: 'Payroll processing', size: 'large', tags: ['payroll'], features: ['Salary calc', 'Withholdings', 'Benefits', 'Pay stubs', 'Direct deposit', 'Compliance'] },
  { id: 'econ-calendar', name: 'Economic Calendar', icon: FaCalendar, category: 'finance-trading', description: 'Economic events', size: 'medium', tags: ['economics'], features: ['Events', 'Impact ratings', 'History', 'Reactions', 'Alerts'] },
  { id: 'dividends', name: 'Dividend Tracker', icon: FaMoneyBillWave, category: 'finance-trading', description: 'Dividend tracking', size: 'medium', tags: ['dividends'], features: ['Calendar', 'Yields', 'Ex-dates', 'History', 'Projections'] },
  { id: 'loan-calc', name: 'Loan Calculator', icon: FaCalculator, category: 'finance-trading', description: 'Loan calculations', size: 'small', tags: ['loans'], features: ['Amortization', 'Payments', 'Extra payments', 'Refinance', 'Comparison'] },
  { id: 'retirement', name: 'Retirement Planner', icon: FaPiggyBank, category: 'finance-trading', description: 'Retirement planning', size: 'large', tags: ['retirement'], features: ['Projections', '401k/IRA', 'Withdrawals', 'Social security', 'Monte Carlo'] },
  { id: 'credit', name: 'Credit Monitor', icon: FaCreditCard, category: 'finance-trading', description: 'Credit monitoring', size: 'medium', tags: ['credit'], features: ['Score tracking', 'Card mgmt', 'Utilization', 'Reminders', 'Fraud alerts'] },

  // ENTERPRISE (18)
  { id: 'crm', name: 'CRM Platform', icon: FaUserTie, category: 'enterprise', description: 'Customer management', size: 'large', tags: ['crm'], features: ['Contacts', 'Pipeline', 'Email', 'Activities', 'Fields', 'Reports'] },
  { id: 'erp', name: 'ERP System', icon: FaBuilding, category: 'enterprise', description: 'Enterprise resource planning', size: 'large', tags: ['erp'], features: ['Financial', 'Inventory', 'Orders', 'Procurement', 'Multi-company', 'Workflows'] },
  { id: 'ppm', name: 'Project Management', icon: FaProjectDiagram, category: 'enterprise', description: 'Enterprise PM', size: 'large', tags: ['ppm'], features: ['Portfolio', 'Resources', 'Gantt', 'Budget', 'Risks', 'Stakeholders'] },
  { id: 'dms', name: 'Document Management', icon: FaFolder, category: 'enterprise', description: 'DMS system', size: 'large', tags: ['dms'], features: ['Version control', 'Permissions', 'Metadata', 'Search', 'Audit', 'Retention'] },
  { id: 'workflow', name: 'Workflow Automation', icon: FaRobot, category: 'enterprise', description: 'Process automation', size: 'large', tags: ['automation'], features: ['Visual builder', 'Approvals', 'Tasks', 'Integrations', 'Forms', 'SLA'] },
  { id: 'knowledge', name: 'Knowledge Base', icon: FaBook, category: 'enterprise', description: 'Internal wiki', size: 'large', tags: ['wiki'], features: ['Rich editor', 'Categories', 'Search', 'Versions', 'Access', 'Templates'] },
  { id: 'helpdesk', name: 'Helpdesk', icon: FaHeadset, category: 'enterprise', description: 'Support platform', size: 'large', tags: ['support'], features: ['Tickets', 'SLA', 'Knowledge', 'Assets', 'Multi-channel', 'Reports'] },
  { id: 'contracts', name: 'Contract Management', icon: FaFileContract, category: 'enterprise', description: 'Contract tracking', size: 'large', tags: ['contracts'], features: ['Repository', 'Expiration', 'Approvals', 'Templates', 'E-sign', 'Reports'] },
  { id: 'vendors', name: 'Vendor Management', icon: FaHandshake, category: 'enterprise', description: 'Supplier management', size: 'large', tags: ['vendors'], features: ['Database', 'Performance', 'Contracts', 'Risk', 'Spend', 'RFP'] },
  { id: 'assets', name: 'Asset Management', icon: FaBoxes, category: 'enterprise', description: 'Asset tracking', size: 'medium', tags: ['assets'], features: ['Register', 'Depreciation', 'Maintenance', 'Scanning', 'Audit', 'Reports'] },
  { id: 'rooms', name: 'Room Booking', icon: FaCalendar, category: 'enterprise', description: 'Resource booking', size: 'medium', tags: ['booking'], features: ['Availability', 'Recurring', 'Equipment', 'Calendar', 'Notifications', 'Analytics'] },
  { id: 'org-chart', name: 'Org Chart', icon: FaSitemap, category: 'enterprise', description: 'Organization charts', size: 'large', tags: ['org'], features: ['Drag-drop', 'Profiles', 'Departments', 'Reporting', 'Export', 'Search'] },
  { id: 'compliance', name: 'Compliance', icon: FaClipboardCheck, category: 'enterprise', description: 'Compliance tracking', size: 'large', tags: ['compliance'], features: ['Requirements', 'Policies', 'Audits', 'Issues', 'Training', 'Reports'] },
  { id: 'bi', name: 'Business Intelligence', icon: FaChartLine, category: 'enterprise', description: 'BI dashboards', size: 'large', tags: ['bi'], features: ['Dashboards', 'KPIs', 'Visuals', 'SQL', 'Reports', 'Drill-down'] },
  { id: 'quality', name: 'Quality Management', icon: FaCertificate, category: 'enterprise', description: 'QMS system', size: 'large', tags: ['quality'], features: ['NCR', 'CAPA', 'Documents', 'Audits', 'Training', 'Metrics'] },
  { id: 'change-mgmt', name: 'Change Management', icon: FaCogs, category: 'enterprise', description: 'Org change', size: 'large', tags: ['change'], features: ['Requests', 'Impact', 'Approvals', 'Comms', 'Training', 'Monitoring'] },
  { id: 'risk-mgmt', name: 'Risk Management', icon: FaShieldAlt, category: 'enterprise', description: 'Enterprise risk', size: 'large', tags: ['risk'], features: ['Register', 'Assessment', 'Mitigation', 'Heat maps', 'Monitoring', 'Reports'] },
  { id: 'strategy', name: 'Strategic Planning', icon: FaBullseye, category: 'enterprise', description: 'Strategy planning', size: 'large', tags: ['strategy'], features: ['Goals', 'Initiatives', 'KPIs', 'Scorecard', 'Progress', 'Reporting'] },

  // SUPPLY CHAIN (12)
  { id: 'inventory', name: 'Inventory', icon: FaWarehouse, category: 'supply-chain', description: 'Inventory control', size: 'large', tags: ['inventory'], features: ['Stock levels', 'Multi-warehouse', 'Scanning', 'Reorder', 'Lot tracking', 'ABC'] },
  { id: 'procurement', name: 'Procurement', icon: FaShoppingCart, category: 'supply-chain', description: 'Purchase orders', size: 'large', tags: ['procurement'], features: ['Requisitions', 'PO mgmt', 'Vendors', 'Approvals', 'Receiving', 'Analytics'] },
  { id: 'warehouse', name: 'Warehouse', icon: FaBoxes, category: 'supply-chain', description: 'Warehouse ops', size: 'large', tags: ['wms'], features: ['Locations', 'Pick/pack/ship', 'Cycle count', 'Kitting', 'Waves', 'Labor'] },
  { id: 'shipping', name: 'Shipping', icon: FaTruck, category: 'supply-chain', description: 'Logistics', size: 'large', tags: ['shipping'], features: ['Carriers', 'Rate shop', 'Labels', 'Tracking', 'BOL', 'Audit'] },
  { id: 'demand', name: 'Demand Planning', icon: FaChartLine, category: 'supply-chain', description: 'Forecasting', size: 'large', tags: ['forecasting'], features: ['Forecasts', 'Seasonality', 'Promos', 'Consensus', 'Safety stock', 'Scenarios'] },
  { id: 'production', name: 'Production Scheduler', icon: FaCalendar, category: 'supply-chain', description: 'Production scheduling', size: 'large', tags: ['scheduling'], features: ['Capacity', 'Work orders', 'Resources', 'Gantt', 'Bottlenecks', 'Updates'] },
  { id: 'qc', name: 'Quality Control', icon: FaCheckSquare, category: 'supply-chain', description: 'Inspection', size: 'medium', tags: ['quality'], features: ['Checklists', 'Defects', 'Sampling', 'Photos', 'Pass/fail', 'Reports'] },
  { id: 'suppliers', name: 'Supplier Portal', icon: FaHandshake, category: 'supply-chain', description: 'Supplier collab', size: 'medium', tags: ['suppliers'], features: ['PO visibility', 'ASN', 'Invoices', 'Metrics', 'Docs', 'Messages'] },
  { id: 'returns', name: 'Returns', icon: FaUndo, category: 'supply-chain', description: 'RMA system', size: 'medium', tags: ['returns'], features: ['RMA', 'Tracking', 'Disposition', 'Refunds', 'Analytics', 'Portal'] },
  { id: 'routing', name: 'Route Optimizer', icon: FaRoute, category: 'supply-chain', description: 'Route optimization', size: 'large', tags: ['routing'], features: ['Optimization', 'Drivers', 'Time windows', 'Capacity', 'Tracking', 'POD'] },
  { id: 'freight', name: 'Freight', icon: FaShip, category: 'supply-chain', description: 'Freight mgmt', size: 'large', tags: ['freight'], features: ['Quotes', 'Booking', 'Tracking', 'Customs', 'International', 'Analytics'] },
  { id: 'mrp', name: 'MRP', icon: FaCogs, category: 'supply-chain', description: 'Material planning', size: 'large', tags: ['mrp'], features: ['BOM', 'Calculations', 'Suggestions', 'Lead times', 'Shortages', 'Planning'] },

  // MARKETING (15)
  { id: 'marketing-auto', name: 'Marketing Automation', icon: FaBullhorn, category: 'marketing-sales', description: 'Marketing campaigns', size: 'large', tags: ['marketing'], features: ['Campaigns', 'Lead scoring', 'Drips', 'A/B test', 'Analytics', 'Segments'] },
  { id: 'email-mkt', name: 'Email Marketing', icon: FaEnvelope, category: 'marketing-sales', description: 'Email campaigns', size: 'large', tags: ['email'], features: ['Builder', 'Templates', 'Lists', 'Automation', 'Analytics', 'Deliverability'] },
  { id: 'social', name: 'Social Media', icon: FaShare, category: 'marketing-sales', description: 'Social management', size: 'large', tags: ['social'], features: ['Multi-platform', 'Calendar', 'Scheduling', 'Analytics', 'Engagement', 'Team'] },
  { id: 'content', name: 'Content Planner', icon: FaCalendar, category: 'marketing-sales', description: 'Content planning', size: 'large', tags: ['content'], features: ['Calendar', 'Briefs', 'Workflow', 'SEO', 'Publishing', 'Performance'] },
  { id: 'seo', name: 'SEO Optimizer', icon: FaSearch, category: 'marketing-sales', description: 'SEO tools', size: 'large', tags: ['seo'], features: ['Keywords', 'Ranking', 'Backlinks', 'Audit', 'Competitors', 'Optimization'] },
  { id: 'landing', name: 'Landing Pages', icon: FaFileAlt, category: 'marketing-sales', description: 'Landing page builder', size: 'large', tags: ['landing'], features: ['Builder', 'Templates', 'A/B test', 'Forms', 'Analytics', 'Mobile'] },
  { id: 'ads', name: 'Ad Campaigns', icon: FaAd, category: 'marketing-sales', description: 'Ad management', size: 'large', tags: ['ads'], features: ['Multi-platform', 'Budget', 'Analytics', 'A/B test', 'ROI', 'Optimization'] },
  { id: 'sales', name: 'Sales Pipeline', icon: FaChartLine, category: 'marketing-sales', description: 'Sales CRM', size: 'large', tags: ['sales'], features: ['Stages', 'Kanban', 'Forecasting', 'Activities', 'Win/loss', 'Quotas'] },
  { id: 'forms', name: 'Lead Forms', icon: FaWpforms, category: 'marketing-sales', description: 'Form builder', size: 'medium', tags: ['forms'], features: ['Builder', 'Logic', 'Spam protection', 'Integrations', 'Analytics', 'Templates'] },
  { id: 'feedback', name: 'Customer Feedback', icon: FaPoll, category: 'marketing-sales', description: 'Surveys', size: 'medium', tags: ['surveys'], features: ['Builder', 'NPS', 'Analysis', 'Sentiment', 'Reports', 'Actions'] },
  { id: 'affiliates', name: 'Affiliates', icon: FaUserFriends, category: 'marketing-sales', description: 'Affiliate program', size: 'large', tags: ['affiliates'], features: ['Tracking', 'Commissions', 'Links', 'Reports', 'Payments', 'Portal'] },
  { id: 'competitors', name: 'Competitor Intel', icon: FaEye, category: 'marketing-sales', description: 'Competitive intelligence', size: 'medium', tags: ['intelligence'], features: ['Tracking', 'Prices', 'Features', 'Analysis', 'Alerts', 'Reports'] },
  { id: 'referrals', name: 'Referrals', icon: FaShare, category: 'marketing-sales', description: 'Referral program', size: 'medium', tags: ['referrals'], features: ['Links', 'Rewards', 'Payouts', 'Analytics', 'Viral loops', 'Portal'] },
  { id: 'sms', name: 'SMS Marketing', icon: FaPhoneAlt, category: 'marketing-sales', description: 'SMS campaigns', size: 'medium', tags: ['sms'], features: ['Builder', 'Lists', 'Automation', 'Analytics', 'Compliance', 'Codes'] },
  { id: 'influencers', name: 'Influencers', icon: FaStar, category: 'marketing-sales', description: 'Influencer marketing', size: 'large', tags: ['influencers'], features: ['Discovery', 'Campaigns', 'Approval', 'Tracking', 'Payments', 'ROI'] },

  // HR (15)
  { id: 'hris', name: 'HR System', icon: FaUserFriends, category: 'hr-team', description: 'HRIS platform', size: 'large', tags: ['hr'], features: ['Database', 'Org chart', 'Docs', 'Onboarding', 'Offboarding', 'Compliance'] },
  { id: 'time', name: 'Time & Attendance', icon: FaClock, category: 'hr-team', description: 'Time tracking', size: 'large', tags: ['time'], features: ['Clock', 'Timesheets', 'PTO', 'Overtime', 'Shifts', 'Mobile'] },
  { id: 'ats', name: 'Recruiting (ATS)', icon: FaUserTie, category: 'hr-team', description: 'Applicant tracking', size: 'large', tags: ['recruiting'], features: ['Jobs', 'Resumes', 'Pipeline', 'Interviews', 'Offers', 'Reports'] },
  { id: 'performance', name: 'Performance', icon: FaMedal, category: 'hr-team', description: 'Performance mgmt', size: 'large', tags: ['performance'], features: ['Reviews', '360 feedback', 'Goals', 'Competencies', 'Development', 'Analytics'] },
  { id: 'lms', name: 'Training (LMS)', icon: FaGraduationCap, category: 'hr-team', description: 'Learning platform', size: 'large', tags: ['training'], features: ['Courses', 'Enrollment', 'Progress', 'Assessments', 'Certs', 'Reports'] },
  { id: 'benefits', name: 'Benefits', icon: FaHeart, category: 'hr-team', description: 'Benefits admin', size: 'large', tags: ['benefits'], features: ['Plans', 'Enrollment', 'Life events', 'COBRA', 'Carriers', 'Reports'] },
  { id: 'engagement', name: 'Engagement', icon: FaHeart, category: 'hr-team', description: 'Employee engagement', size: 'medium', tags: ['engagement'], features: ['Surveys', 'eNPS', 'Recognition', 'Feedback', 'Analytics', 'Actions'] },
  { id: 'shifts', name: 'Shift Scheduler', icon: FaCalendar, category: 'hr-team', description: 'Shift scheduling', size: 'large', tags: ['shifts'], features: ['Templates', 'Drag-drop', 'Availability', 'Swaps', 'Costs', 'Notifications'] },
  { id: 'directory', name: 'Directory', icon: FaAddressBook, category: 'hr-team', description: 'Employee directory', size: 'medium', tags: ['directory'], features: ['Profiles', 'Search', 'Org view', 'Skills', 'Contact', 'Photos'] },
  { id: 'okrs', name: 'OKRs', icon: FaBullseye, category: 'hr-team', description: 'OKR tracking', size: 'large', tags: ['okr'], features: ['Cascading', 'Progress', 'Check-ins', 'Alignment', 'Reports', 'Integrations'] },
  { id: 'collab', name: 'Collaboration', icon: FaUsers, category: 'hr-team', description: 'Team collaboration', size: 'large', tags: ['collaboration'], features: ['Channels', 'Files', 'Tasks', 'Video', 'Screen share', 'Integrations'] },
  { id: 'succession', name: 'Succession', icon: FaSitemap, category: 'hr-team', description: 'Succession planning', size: 'large', tags: ['succession'], features: ['Talent pools', 'Charts', 'Readiness', 'Development', 'Risk', 'Reports'] },
  { id: 'comp', name: 'Compensation', icon: FaDollarSign, category: 'hr-team', description: 'Comp management', size: 'large', tags: ['compensation'], features: ['Bands', 'Merit', 'Bonuses', 'Equity', 'Benchmarking', 'Statements'] },
  { id: 'ess', name: 'Self-Service', icon: FaUserTie, category: 'hr-team', description: 'Employee portal', size: 'medium', tags: ['self-service'], features: ['Info updates', 'PTO', 'Payslips', 'Benefits', 'Tax forms', 'Directory'] },
  { id: 'hr-analytics', name: 'HR Analytics', icon: FaChartBar, category: 'hr-team', description: 'People analytics', size: 'large', tags: ['analytics'], features: ['Headcount', 'Turnover', 'Time-to-fill', 'Diversity', 'Comp equity', 'Attrition'] },

  // LEGAL (10)
  { id: 'legal-clm', name: 'Contract Lifecycle', icon: FaFileContract, category: 'legal-compliance', description: 'Contract management', size: 'large', tags: ['contracts'], features: ['Repository', 'Lifecycle', 'Approvals', 'Templates', 'E-sign', 'Renewals'] },
  { id: 'legal-matter', name: 'Matter Management', icon: FaGavel, category: 'legal-compliance', description: 'Legal matters', size: 'large', tags: ['legal'], features: ['Matters', 'Time & billing', 'Docs', 'Calendar', 'Portal', 'Reports'] },
  { id: 'ip', name: 'IP Portfolio', icon: FaCertificate, category: 'legal-compliance', description: 'IP management', size: 'large', tags: ['ip'], features: ['Patents', 'Trademarks', 'Renewals', 'Licensing', 'Valuation', 'Reports'] },
  { id: 'litigation', name: 'Litigation', icon: FaGavel, category: 'legal-compliance', description: 'Case management', size: 'large', tags: ['litigation'], features: ['Cases', 'Discovery', 'Deadlines', 'Evidence', 'Correspondence', 'Reports'] },
  { id: 'compliance-track', name: 'Compliance Tracker', icon: FaClipboardCheck, category: 'legal-compliance', description: 'Regulatory compliance', size: 'large', tags: ['compliance'], features: ['Requirements', 'Calendar', 'Issues', 'Reports', 'Audit', 'Training'] },
  { id: 'regulatory', name: 'Regulatory Change', icon: FaBell, category: 'legal-compliance', description: 'Reg monitoring', size: 'medium', tags: ['regulatory'], features: ['Monitoring', 'Impact', 'Tracking', 'Notifications', 'Updates', 'Reports'] },
  { id: 'ediscovery', name: 'E-Discovery', icon: FaSearch, category: 'legal-compliance', description: 'Electronic discovery', size: 'large', tags: ['ediscovery'], features: ['Collection', 'Processing', 'Review', 'Privilege', 'Production', 'Analytics'] },
  { id: 'legal-billing', name: 'Legal Billing', icon: FaDollarSign, category: 'legal-compliance', description: 'Time & billing', size: 'large', tags: ['billing'], features: ['Time entry', 'Expenses', 'Invoices', 'Trust', 'Reports', 'Collections'] },
  { id: 'ndas', name: 'NDAs', icon: FaFileContract, category: 'legal-compliance', description: 'NDA management', size: 'medium', tags: ['nda'], features: ['Templates', 'Approvals', 'Versions', 'Signatures', 'Expiration', 'Repository'] },
  { id: 'doc-gen', name: 'Doc Generator', icon: FaFileAlt, category: 'legal-compliance', description: 'Document automation', size: 'medium', tags: ['documents'], features: ['Templates', 'Variables', 'Clauses', 'Versions', 'PDF', 'E-sign'] },

  // REAL ESTATE (10)
  { id: 'prop-mgmt', name: 'Property Management', icon: FaBuilding, category: 'real-estate', description: 'Property management', size: 'large', tags: ['property'], features: ['Portfolio', 'Units', 'Tenants', 'Maintenance', 'Inspections', 'Reports'] },
  { id: 'leases', name: 'Lease Management', icon: FaFileContract, category: 'real-estate', description: 'Lease tracking', size: 'large', tags: ['leases'], features: ['Tracking', 'Renewals', 'Escalations', 'Terms', 'Docs', 'Reports'] },
  { id: 'maintenance', name: 'Maintenance', icon: FaWrench, category: 'real-estate', description: 'Work orders', size: 'medium', tags: ['maintenance'], features: ['Requests', 'Work orders', 'Vendors', 'Priority', 'Status', 'History'] },
  { id: 'tenant-portal', name: 'Tenant Portal', icon: FaUsers, category: 'real-estate', description: 'Tenant self-service', size: 'medium', tags: ['tenants'], features: ['Payments', 'Requests', 'Docs', 'Comms', 'Lease', 'Announcements'] },
  { id: 'listings', name: 'Listings', icon: FaHome, category: 'real-estate', description: 'Property listings', size: 'large', tags: ['listings'], features: ['Properties', 'Photos', 'Tours', 'Leads', 'Inquiries', 'Marketing'] },
  { id: 'rent', name: 'Rent Collection', icon: FaDollarSign, category: 'real-estate', description: 'Rent payments', size: 'medium', tags: ['rent'], features: ['Payments', 'Auto-pay', 'Late fees', 'History', 'Receipts', 'Reports'] },
  { id: 'inspections', name: 'Inspections', icon: FaEye, category: 'real-estate', description: 'Property inspections', size: 'medium', tags: ['inspections'], features: ['Scheduling', 'Checklists', 'Photos', 'Issues', 'Reports', 'History'] },
  { id: 're-vendors', name: 'RE Vendors', icon: FaHandshake, category: 'real-estate', description: 'Contractor mgmt', size: 'medium', tags: ['vendors'], features: ['Database', 'Licenses', 'Insurance', 'Ratings', 'Work', 'Payments'] },
  { id: 're-crm', name: 'Real Estate CRM', icon: FaUserTie, category: 'real-estate', description: 'Client management', size: 'large', tags: ['crm'], features: ['Leads', 'Clients', 'Transactions', 'Comms', 'Tasks', 'Reports'] },
  { id: 'prop-analytics', name: 'Property Analytics', icon: FaChartBar, category: 'real-estate', description: 'Property metrics', size: 'large', tags: ['analytics'], features: ['Occupancy', 'Revenue', 'Expenses', 'ROI', 'Trends', 'Dashboards'] },

  // HEALTHCARE (12)
  { id: 'ehr', name: 'EHR', icon: FaHospital, category: 'healthcare', description: 'Electronic health records', size: 'large', tags: ['ehr'], features: ['Demographics', 'History', 'Medications', 'Notes', 'Labs', 'HIPAA'] },
  { id: 'scheduling', name: 'Scheduling', icon: FaCalendar, category: 'healthcare', description: 'Appointments', size: 'large', tags: ['scheduling'], features: ['Calendar', 'Reminders', 'Waitlist', 'Providers', 'No-show', 'Insurance'] },
  { id: 'billing', name: 'Medical Billing', icon: FaFileInvoice, category: 'healthcare', description: 'Healthcare billing', size: 'large', tags: ['billing'], features: ['Claims', 'Insurance', 'Posting', 'Denials', 'Statements', 'Reports'] },
  { id: 'rx', name: 'Prescriptions', icon: FaPills, category: 'healthcare', description: 'E-prescribing', size: 'medium', tags: ['prescriptions'], features: ['E-prescribe', 'History', 'Interactions', 'Pharmacy', 'Refills', 'Controlled'] },
  { id: 'labs', name: 'Lab Results', icon: FaVial, category: 'healthcare', description: 'Lab tracking', size: 'medium', tags: ['labs'], features: ['Orders', 'Results', 'Critical values', 'Trending', 'Integration', 'Portal'] },
  { id: 'telehealth', name: 'Telehealth', icon: FaVideo, category: 'healthcare', description: 'Virtual visits', size: 'large', tags: ['telehealth'], features: ['Video', 'Waiting room', 'Screen share', 'Chat', 'Recording', 'HIPAA'] },
  { id: 'patient-portal', name: 'Patient Portal', icon: FaUsers, category: 'healthcare', description: 'Patient access', size: 'large', tags: ['portal'], features: ['Scheduling', 'Records', 'Messaging', 'Billing', 'Labs', 'Forms'] },
  { id: 'imaging', name: 'Imaging', icon: FaXRay, category: 'healthcare', description: 'PACS viewer', size: 'large', tags: ['imaging'], features: ['DICOM', 'Storage', 'Annotations', 'Measurements', 'Comparison', 'Sharing'] },
  { id: 'cds', name: 'Clinical Decision', icon: FaBrain, category: 'healthcare', description: 'Clinical guidelines', size: 'medium', tags: ['clinical'], features: ['Alerts', 'Interactions', 'Guidelines', 'Order sets', 'Protocols', 'Documentation'] },
  { id: 'immunizations', name: 'Immunizations', icon: FaSyringe, category: 'healthcare', description: 'Vaccine mgmt', size: 'medium', tags: ['vaccines'], features: ['Scheduling', 'History', 'Registry', 'Inventory', 'Reminders', 'Documentation'] },
  { id: 'chronic-care', name: 'Chronic Care', icon: FaHeartbeat, category: 'healthcare', description: 'Care management', size: 'large', tags: ['chronic'], features: ['Care plans', 'Goals', 'Education', 'Monitoring', 'Alerts', 'Reports'] },
  { id: 'health-analytics', name: 'Health Analytics', icon: FaChartBar, category: 'healthcare', description: 'Clinical analytics', size: 'large', tags: ['analytics'], features: ['Quality', 'Population', 'Utilization', 'Outcomes', 'Dashboards', 'Reports'] },

  // MANUFACTURING (10)
  { id: 'mes', name: 'MES', icon: FaIndustry, category: 'manufacturing', description: 'Manufacturing execution', size: 'large', tags: ['mes'], features: ['Production', 'Work orders', 'Materials', 'Quality', 'Downtime', 'Reports'] },
  { id: 'shop-floor', name: 'Shop Floor', icon: FaCogs, category: 'manufacturing', description: 'Shop floor control', size: 'large', tags: ['shopfloor'], features: ['Scheduling', 'Work centers', 'Capacity', 'Routing', 'Labor', 'Status'] },
  { id: 'cmms', name: 'CMMS', icon: FaWrench, category: 'manufacturing', description: 'Maintenance mgmt', size: 'large', tags: ['maintenance'], features: ['Preventive', 'Work orders', 'Assets', 'Parts', 'Scheduling', 'Reports'] },
  { id: 'oee', name: 'OEE', icon: FaChartLine, category: 'manufacturing', description: 'Equipment effectiveness', size: 'medium', tags: ['oee'], features: ['Calculations', 'Availability', 'Performance', 'Quality', 'Downtime', 'Dashboards'] },
  { id: 'spc', name: 'SPC', icon: FaChartBar, category: 'manufacturing', description: 'Statistical control', size: 'medium', tags: ['spc'], features: ['Control charts', 'Cp/Cpk', 'Sampling', 'Detection', 'Trends', 'Reports'] },
  { id: 'bom', name: 'BOM Manager', icon: FaListUl, category: 'manufacturing', description: 'Bill of materials', size: 'large', tags: ['bom'], features: ['Multi-level', 'Versions', 'ECO', 'Costing', 'Where-used', 'Export'] },
  { id: 'tools', name: 'Tool Management', icon: FaTools, category: 'manufacturing', description: 'Tool tracking', size: 'medium', tags: ['tools'], features: ['Inventory', 'Calibration', 'Maintenance', 'Checkout', 'History', 'Reports'] },
  { id: 'prod-analytics', name: 'Production Analytics', icon: FaChartPie, category: 'manufacturing', description: 'Mfg metrics', size: 'large', tags: ['analytics'], features: ['Metrics', 'Efficiency', 'Scrap', 'Labor', 'Dashboards', 'Reports'] },
  { id: 'downtime', name: 'Downtime', icon: FaClock, category: 'manufacturing', description: 'Downtime tracking', size: 'medium', tags: ['downtime'], features: ['Logging', 'Reasons', 'Duration', 'Pareto', 'Trends', 'Reports'] },
  { id: 'yield', name: 'Yield', icon: FaPercentage, category: 'manufacturing', description: 'Yield tracking', size: 'medium', tags: ['yield'], features: ['Calculations', 'Scrap', 'Rework', 'Costs', 'Trends', 'Reports'] },

  // SCIENCE & MATH (10)
  { id: 'sci-calc', name: 'Scientific Calculator', icon: FaCalculator, category: 'science-math', description: 'Advanced calculator', size: 'large', tags: ['calculator'], features: ['Functions', 'Graphing', 'Algebra', 'Conversions', 'Matrix', 'Statistics'] },
  { id: 'chemistry', name: 'Chemistry Lab', icon: FaFlask, category: 'science-math', description: 'Chemistry tools', size: 'large', tags: ['chemistry'], features: ['Periodic table', 'Molecular viewer', 'Equations', 'Molarity', 'Reactions', 'Properties'] },
  { id: 'physics', name: 'Physics Simulator', icon: FaAtom, category: 'science-math', description: 'Physics experiments', size: 'large', tags: ['physics'], features: ['Motion sims', 'Forces', 'Waves', 'Optics', 'Circuits', 'Projectile'] },
  { id: 'math', name: 'Math Toolkit', icon: FaSquareRootAlt, category: 'science-math', description: 'Math tools', size: 'large', tags: ['math'], features: ['Derivatives', 'Integrals', 'Matrix', 'Statistics', 'Probability', 'Sequences'] },
  { id: 'converter', name: 'Unit Converter', icon: FaBalanceScale, category: 'science-math', description: 'Unit conversions', size: 'small', tags: ['converter'], features: ['Length/mass/volume', 'Temperature', 'Energy', 'Custom', 'Currency', 'History'] },
  { id: 'graphing', name: 'Graphing Calculator', icon: FaChartLine, category: 'science-math', description: 'Plot functions', size: 'large', tags: ['graphing'], features: ['2D plotting', 'Parametric', 'Polar', '3D surfaces', 'Zoom', 'Export'] },
  { id: 'stats', name: 'Statistics Lab', icon: FaChartPie, category: 'science-math', description: 'Statistical analysis', size: 'large', tags: ['statistics'], features: ['Descriptive', 'Hypothesis', 'Regression', 'ANOVA', 'Distribution', 'Confidence'] },
  { id: 'equations', name: 'Equation Solver', icon: FaInfinity, category: 'science-math', description: 'Solve equations', size: 'medium', tags: ['equations'], features: ['Linear', 'Quadratic', 'Systems', 'Differential', 'Step-by-step', 'Verify'] },
  { id: 'periodic', name: 'Periodic Table', icon: FaAtom, category: 'science-math', description: 'Interactive periodic table', size: 'large', tags: ['chemistry'], features: ['Properties', 'Electrons', 'Data', 'Trends', 'Groups', 'Search'] },
  { id: 'molecules', name: 'Molecular Viewer', icon: FaVial, category: 'science-math', description: '3D molecules', size: 'large', tags: ['chemistry'], features: ['3D rendering', 'Rotation', 'Bonds', 'Properties', 'Export', 'Library'] },

  // ENGINEERING (10)
  { id: 'circuit', name: 'Circuit Designer', icon: FaMicrochip, category: 'engineering', description: 'Electronic circuits', size: 'large', tags: ['electronics'], features: ['Components', 'Schematic', 'SPICE sim', 'Oscilloscope', 'PCB', 'Netlist'] },
  { id: 'cad', name: 'CAD Viewer', icon: FaCube, category: 'engineering', description: 'View CAD models', size: 'large', tags: ['cad'], features: ['Import STL/OBJ', '3D navigation', 'Measurements', 'Cross-sections', 'Annotations', 'Export'] },
  { id: 'eng-notebook', name: 'Engineering Notebook', icon: FaPencilRuler, category: 'engineering', description: 'Design documentation', size: 'large', tags: ['documentation'], features: ['Calculations', 'Drawings', 'Photos', 'Units', 'Versions', 'PDF'] },
  { id: 'structural', name: 'Structural Calculator', icon: FaDraftingCompass, category: 'engineering', description: 'Structural analysis', size: 'medium', tags: ['structural'], features: ['Beams', 'Stress', 'Materials', 'Loads', 'Safety', 'Codes'] },
  { id: 'control', name: 'Control Systems', icon: FaCogs, category: 'engineering', description: 'Control design', size: 'large', tags: ['control'], features: ['Block diagrams', 'PID tuning', 'Bode', 'Step response', 'Stability', 'State space'] },
  { id: 'fea', name: 'FEA', icon: FaCube, category: 'engineering', description: 'Finite element analysis', size: 'large', tags: ['fea'], features: ['Mesh', 'Stress', 'Thermal', 'Modal', 'Visualization', 'Export'] },
  { id: 'signals', name: 'Signal Processing', icon: FaWaveSquare, category: 'engineering', description: 'Signal analysis', size: 'large', tags: ['dsp'], features: ['FFT', 'Filtering', 'Spectrograms', 'Generation', 'Manipulation', 'Export'] },
  { id: 'electrical', name: 'Electrical Calculator', icon: FaBolt, category: 'engineering', description: 'Electrical calcs', size: 'medium', tags: ['electrical'], features: ['Load calc', 'Wire sizing', 'Voltage drop', 'Power factor', 'NEC', 'Reports'] },
  { id: 'hvac', name: 'HVAC Design', icon: FaWind, category: 'engineering', description: 'HVAC calculations', size: 'large', tags: ['hvac'], features: ['Load calc', 'Duct sizing', 'Equipment', 'Energy', 'Ventilation', 'Reports'] },
  { id: 'robotics', name: 'Robotics Simulator', icon: FaRobot, category: 'engineering', description: 'Robot simulation', size: 'large', tags: ['robotics'], features: ['Kinematics', 'Path planning', 'Collision', '3D view', 'Programming', 'Export'] },

  // DEVELOPER TOOLS (15)
  { id: 'snippets', name: 'Code Snippets', icon: FaFileCode, category: 'developer-tools', description: 'Snippet manager', size: 'large', tags: ['code'], features: ['Multi-language', 'Syntax highlight', 'Tags', 'Search', 'Execute', 'Share'] },
  { id: 'api', name: 'API Tester', icon: FaNetworkWired, category: 'developer-tools', description: 'Test REST APIs', size: 'large', tags: ['api'], features: ['HTTP methods', 'Headers', 'History', 'Collections', 'Environments', 'Response'] },
  { id: 'regex', name: 'Regex Tester', icon: FaCode, category: 'developer-tools', description: 'Test regex', size: 'medium', tags: ['regex'], features: ['Live matching', 'Groups', 'Patterns', 'Cheat sheet', 'Multi-line'] },
  { id: 'json', name: 'JSON Formatter', icon: FaFileCode, category: 'developer-tools', description: 'Format JSON/XML', size: 'medium', tags: ['json'], features: ['Beautify/minify', 'Validation', 'Tree view', 'Conversion', 'Path', 'Diff'] },
  { id: 'git', name: 'Git Workflow', icon: FaGitAlt, category: 'developer-tools', description: 'Git tracking', size: 'medium', tags: ['git'], features: ['Commits', 'Branches', 'PRs', 'Conflicts', 'Release notes'] },
  { id: 'db-query', name: 'DB Query Builder', icon: FaDatabase, category: 'developer-tools', description: 'Visual SQL', size: 'large', tags: ['database'], features: ['Visual builder', 'Syntax help', 'History', 'Export', 'Schema'] },
  { id: 'colors', name: 'Color Generator', icon: FaPalette, category: 'developer-tools', description: 'Color tools', size: 'small', tags: ['colors'], features: ['Picker', 'Palettes', 'Gradients', 'Contrast', 'Export'] },
  { id: 'markdown', name: 'Markdown Editor', icon: FaEdit, category: 'developer-tools', description: 'Markdown editor', size: 'large', tags: ['markdown'], features: ['Live preview', 'Syntax', 'Tables', 'Code', 'Export'] },
  { id: 'diff', name: 'Diff Viewer', icon: FaCode, category: 'developer-tools', description: 'Compare code', size: 'medium', tags: ['diff'], features: ['Side-by-side', 'Syntax', 'Line numbers', 'Conflicts', 'Export'] },
  { id: 'base64', name: 'Base64 Encoder', icon: FaKey, category: 'developer-tools', description: 'Encode/decode', size: 'small', tags: ['encoding'], features: ['Encode text', 'Decode', 'Files', 'URL safe', 'Copy'] },
  { id: 'jwt', name: 'JWT Debugger', icon: FaLock, category: 'developer-tools', description: 'Debug JWT', size: 'medium', tags: ['jwt'], features: ['Decode', 'Verify', 'Claims', 'Algorithms', 'Generate'] },
  { id: 'cron', name: 'Cron Builder', icon: FaClock, category: 'developer-tools', description: 'Build cron', size: 'small', tags: ['cron'], features: ['Visual', 'Parser', 'Next runs', 'Patterns', 'Docs'] },
  { id: 'api-docs', name: 'API Docs', icon: FaBook, category: 'developer-tools', description: 'API documentation', size: 'large', tags: ['api'], features: ['OpenAPI', 'Interactive', 'Examples', 'Try it', 'Export'] },
  { id: 'webhook', name: 'Webhook Tester', icon: FaNetworkWired, category: 'developer-tools', description: 'Test webhooks', size: 'medium', tags: ['webhooks'], features: ['Unique URLs', 'Inspection', 'Config', 'History', 'Replay'] },
  { id: 'sql-opt', name: 'SQL Optimizer', icon: FaDatabase, category: 'developer-tools', description: 'Optimize SQL', size: 'medium', tags: ['sql'], features: ['Explain', 'Tips', 'Indexes', 'Format', 'Plan'] },

  // DATA ANALYTICS (10)
  { id: 'viz', name: 'Data Visualizer', icon: FaChartBar, category: 'data-analysis', description: 'Create charts', size: 'large', tags: ['charts'], features: ['Bar/line/pie/scatter', 'Import CSV', 'Interactive', 'Styling', 'Export', 'Dashboards'] },
  { id: 'spreadsheet', name: 'Spreadsheet', icon: FaTable, category: 'data-analysis', description: 'Smart spreadsheet', size: 'large', tags: ['spreadsheet'], features: ['Formulas', 'Pivots', 'Charts', 'Validation', 'Import/export', 'Collab'] },
  { id: 'data-clean', name: 'Data Cleaner', icon: FaFilter, category: 'data-analysis', description: 'Clean datasets', size: 'medium', tags: ['cleaning'], features: ['Duplicates', 'Missing values', 'Types', 'Normalization', 'Operations'] },
  { id: 'sql-analyze', name: 'SQL Analyzer', icon: FaDatabase, category: 'data-analysis', description: 'Analyze SQL', size: 'medium', tags: ['sql'], features: ['Explain', 'Tips', 'Indexes', 'Format'] },
  { id: 'pivot', name: 'Pivot Builder', icon: FaTable, category: 'data-analysis', description: 'Pivot tables', size: 'large', tags: ['pivot'], features: ['Drag-drop', 'Aggregations', 'Filters', 'Sorting', 'Export', 'Visuals'] },
  { id: 'dashboard', name: 'Dashboard Creator', icon: FaChartLine, category: 'data-analysis', description: 'Build dashboards', size: 'large', tags: ['dashboards'], features: ['Drag-drop', 'Live data', 'KPIs', 'Filters', 'Sharing', 'Refresh'] },
  { id: 'reports', name: 'Report Builder', icon: FaFileAlt, category: 'data-analysis', description: 'Create reports', size: 'large', tags: ['reports'], features: ['Designer', 'Data sources', 'Formatting', 'Parameters', 'Scheduling', 'Export'] },
  { id: 'etl', name: 'ETL Tool', icon: FaDatabase, category: 'data-analysis', description: 'Extract/transform/load', size: 'large', tags: ['etl'], features: ['Connectors', 'Transforms', 'Scheduling', 'Errors', 'Monitoring', 'Logging'] },
  { id: 'profiler', name: 'Data Profiler', icon: FaSearch, category: 'data-analysis', description: 'Profile datasets', size: 'medium', tags: ['profiling'], features: ['Summary', 'Missing', 'Distributions', 'Patterns', 'Quality', 'Reports'] },
  { id: 'ml', name: 'Predictive Analytics', icon: FaBrain, category: 'data-analysis', description: 'Predictive modeling', size: 'large', tags: ['ml'], features: ['Training', 'Predictions', 'Features', 'Accuracy', 'Visuals', 'Export'] },

  // RESEARCH (8)
  { id: 'research', name: 'Research Notes', icon: FaMicroscope, category: 'research', description: 'Literature review', size: 'large', tags: ['research'], features: ['Annotations', 'Citations', 'Bibliography', 'Questions', 'Map', 'BibTeX'] },
  { id: 'lab', name: 'Lab Notebook', icon: FaVial, category: 'research', description: 'Electronic lab notebook', size: 'large', tags: ['lab'], features: ['Experiments', 'Protocols', 'Results', 'Photos', 'Versions', 'Compliance'] },
  { id: 'hypothesis', name: 'Hypothesis Tracker', icon: FaLightbulb, category: 'research', description: 'Track hypotheses', size: 'medium', tags: ['hypotheses'], features: ['Logging', 'Predictions', 'Results', 'Statistics', 'Evidence'] },
  { id: 'references', name: 'Reference Manager', icon: FaBook, category: 'research', description: 'Organize papers', size: 'large', tags: ['references'], features: ['Import DOI', 'PDFs', 'Tags', 'Styles', 'Export', 'Search'] },
  { id: 'citations', name: 'Citation Generator', icon: FaFileAlt, category: 'research', description: 'Generate citations', size: 'small', tags: ['citations'], features: ['Styles (APA/MLA)', 'Auto-fill DOI', 'Copy', 'Export', 'Bibliography'] },
  { id: 'lit-review', name: 'Literature Matrix', icon: FaTable, category: 'research', description: 'Review matrix', size: 'large', tags: ['literature'], features: ['Comparison', 'Themes', 'Gap analysis', 'Notes', 'Export', 'Synthesis'] },
  { id: 'grants', name: 'Grant Tracker', icon: FaDollarSign, category: 'research', description: 'Track grants', size: 'medium', tags: ['grants'], features: ['Database', 'Deadlines', 'Applications', 'Budget', 'Reports', 'Docs'] },
  { id: 'experiments', name: 'Experiment Planner', icon: FaFlask, category: 'research', description: 'Plan experiments', size: 'large', tags: ['experiments'], features: ['Design', 'Variables', 'Controls', 'Sample size', 'Protocols', 'Checklist'] },

  // DESIGN & CREATIVE (15)
  { id: 'video', name: 'Video Editor', icon: FaVideo, category: 'design-creative', description: 'Video editing', size: 'large', tags: ['video'], features: ['Timeline', 'Transitions', 'Audio', 'Grading', 'Titles', 'Export'] },
  { id: '3d', name: '3D Modeling', icon: FaCube, category: 'design-creative', description: '3D modeling', size: 'large', tags: ['3d'], features: ['Mesh', 'Texturing', 'Lighting', 'Tracing', 'Animation', 'Export'] },
  { id: 'animation', name: 'Animation Tool', icon: FaFilm, category: 'design-creative', description: '2D/3D animation', size: 'large', tags: ['animation'], features: ['Keyframes', 'Rigging', 'Motion', 'Particles', 'Camera', 'Timeline'] },
  { id: 'audio', name: 'Audio Production', icon: FaMusic, category: 'design-creative', description: 'Music production', size: 'large', tags: ['audio'], features: ['Multi-track', 'VST', 'MIDI', 'Mixing', 'Mastering', 'Export'] },
  { id: 'graphics', name: 'Graphic Design', icon: FaPaintBrush, category: 'design-creative', description: 'Graphic design', size: 'large', tags: ['design'], features: ['Vector', 'Layers', 'Typography', 'Colors', 'Templates', 'Export'] },
  { id: 'photo', name: 'Photo Editor', icon: FaCamera, category: 'design-creative', description: 'Photo editing', size: 'large', tags: ['photo'], features: ['RAW', 'Non-destructive', 'Filters', 'Retouching', 'Batch', 'Presets'] },
  { id: 'ui-ux', name: 'UI/UX Design', icon: FaLayerGroup, category: 'design-creative', description: 'Interface design', size: 'large', tags: ['ui'], features: ['Artboards', 'Components', 'Prototyping', 'Collab', 'Systems', 'Handoff'] },
  { id: 'brand', name: 'Brand Kit', icon: FaPalette, category: 'design-creative', description: 'Brand assets', size: 'medium', tags: ['branding'], features: ['Logos', 'Colors', 'Typography', 'Assets', 'Guidelines', 'Access'] },
  { id: 'print', name: 'Print Designer', icon: FaFileAlt, category: 'design-creative', description: 'Print layouts', size: 'large', tags: ['print'], features: ['Layout', 'Masters', 'CMYK', 'Bleed', 'Preflight', 'PDF'] },
  { id: 'dam', name: 'Asset Manager', icon: FaFolder, category: 'design-creative', description: 'Asset library', size: 'large', tags: ['dam'], features: ['Library', 'Metadata', 'Search', 'Versions', 'Sharing', 'Rights'] },
  { id: 'color-scheme', name: 'Color Schemes', icon: FaPalette, category: 'design-creative', description: 'Color palettes', size: 'small', tags: ['colors'], features: ['Harmony', 'Generation', 'Gradients', 'Contrast', 'Export', 'Inspiration'] },
  { id: 'typography', name: 'Typography', icon: FaEdit, category: 'design-creative', description: 'Test fonts', size: 'medium', tags: ['typography'], features: ['Preview', 'Scale', 'Pairing', 'Custom', 'Export'] },
  { id: 'wireframe', name: 'Wireframe', icon: FaLayerGroup, category: 'design-creative', description: 'Wireframing', size: 'large', tags: ['wireframe'], features: ['Components', 'Drag-drop', 'Grid', 'Export', 'Preview'] },
  { id: 'icons', name: 'Icon Designer', icon: FaStar, category: 'design-creative', description: 'Create icons', size: 'medium', tags: ['icons'], features: ['Vector', 'Grid', 'Export', 'Presets', 'Sets'] },
  { id: 'logo', name: 'Logo Maker', icon: FaPalette, category: 'design-creative', description: 'Design logos', size: 'medium', tags: ['logo'], features: ['Templates', 'Shapes', 'Typography', 'Colors', 'Export', 'Kit'] },

  // COMMUNICATION (10)
  { id: 'email-client', name: 'Email Client', icon: FaEnvelope, category: 'communication', description: 'Email management', size: 'large', tags: ['email'], features: ['Multi-account', 'Folders', 'Search', 'Attachments', 'Signatures', 'Templates'] },
  { id: 'messaging', name: 'Team Messaging', icon: FaComments, category: 'communication', description: 'Team chat', size: 'large', tags: ['chat'], features: ['Channels', 'DMs', 'Files', 'Search', 'Notifications', 'Integrations'] },
  { id: 'video-conf', name: 'Video Conferencing', icon: FaVideo, category: 'communication', description: 'Video meetings', size: 'large', tags: ['video'], features: ['HD video', 'Screen share', 'Recording', 'Chat', 'Backgrounds', 'Breakout'] },
  { id: 'voip', name: 'VoIP Phone', icon: FaPhoneAlt, category: 'communication', description: 'Business phone', size: 'large', tags: ['phone'], features: ['Routing', 'Voicemail', 'Recording', 'Conference', 'Analytics', 'Mobile'] },
  { id: 'email-templates', name: 'Email Templates', icon: FaEnvelope, category: 'communication', description: 'Email templates', size: 'medium', tags: ['templates'], features: ['Library', 'Variables', 'Categories', 'Search', 'Preview'] },
  { id: 'call-log', name: 'Call Logger', icon: FaPhoneAlt, category: 'communication', description: 'Log calls', size: 'medium', tags: ['calls'], features: ['Log', 'Contact', 'Follow-ups', 'Notes', 'Duration'] },
  { id: 'contacts', name: 'Contact Manager', icon: FaAddressBook, category: 'communication', description: 'Manage contacts', size: 'medium', tags: ['contacts'], features: ['Database', 'Groups', 'Tags', 'Search', 'Import/export', 'Sync'] },
  { id: 'newsletter', name: 'Newsletter', icon: FaNewspaper, category: 'communication', description: 'Create newsletters', size: 'large', tags: ['newsletter'], features: ['Editor', 'Templates', 'Lists', 'Analytics', 'Scheduling', 'A/B test'] },
  { id: 'chatbot', name: 'Chatbot Builder', icon: FaRobot, category: 'communication', description: 'Build chatbots', size: 'large', tags: ['chatbot'], features: ['Visual', 'Flows', 'Integrations', 'Analytics', 'Multi-channel', 'Templates'] },
  { id: 'comm-analytics', name: 'Comm Analytics', icon: FaChartBar, category: 'communication', description: 'Comm metrics', size: 'medium', tags: ['analytics'], features: ['Email metrics', 'Call analytics', 'Response times', 'Engagement', 'Dashboards', 'Reports'] },

  // PERSONAL LIFE (12)
  { id: 'journal', name: 'Journal', icon: FaBook, category: 'personal-life', description: 'Daily journaling', size: 'large', tags: ['journal'], features: ['Rich text', 'Mood tracking', 'Tags', 'Search', 'Streaks', 'Privacy'] },
  { id: 'habits', name: 'Habit Tracker', icon: FaCheckSquare, category: 'personal-life', description: 'Track habits', size: 'medium', tags: ['habits'], features: ['Custom', 'Check-in', 'Streaks', 'Calendar', 'Reminders'] },
  { id: 'personal-goals', name: 'Goals', icon: FaBullseye, category: 'personal-life', description: 'Personal goals', size: 'medium', tags: ['goals'], features: ['SMART', 'Milestones', 'Progress', 'Deadlines', 'Visual'] },
  { id: 'books', name: 'Reading List', icon: FaBook, category: 'personal-life', description: 'Track books', size: 'medium', tags: ['reading'], features: ['List', 'Progress', 'Ratings', 'Stats', 'Recommendations'] },
  { id: 'photos', name: 'Photo Album', icon: FaCamera, category: 'personal-life', description: 'Photo organization', size: 'large', tags: ['photos'], features: ['Upload', 'Albums', 'Captions', 'Timeline', 'Share'] },
  { id: 'timeline', name: 'Life Timeline', icon: FaCalendar, category: 'personal-life', description: 'Life events', size: 'large', tags: ['timeline'], features: ['Events', 'Timeline', 'Photos', 'Milestones', 'Categories', 'Export'] },
  { id: 'gratitude', name: 'Gratitude Journal', icon: FaHeart, category: 'personal-life', description: 'Daily gratitude', size: 'medium', tags: ['gratitude'], features: ['Prompts', 'Entries', 'Streaks', 'Reflections', 'Themes', 'Stats'] },
  { id: 'mood', name: 'Mood Tracker', icon: FaHeart, category: 'personal-life', description: 'Track moods', size: 'medium', tags: ['mood'], features: ['Logging', 'Emotions', 'Trends', 'Triggers', 'Notes', 'Visuals'] },
  { id: 'vision', name: 'Vision Board', icon: FaStar, category: 'personal-life', description: 'Visual goals', size: 'large', tags: ['vision'], features: ['Images', 'Categories', 'Affirmations', 'Creation', 'Share', 'Progress'] },
  { id: 'affirmations', name: 'Affirmations', icon: FaHeart, category: 'personal-life', description: 'Positive affirmations', size: 'small', tags: ['affirmations'], features: ['Library', 'Daily', 'Custom', 'Categories', 'Reminders'] },
  { id: 'memory', name: 'Memory Box', icon: FaArchive, category: 'personal-life', description: 'Store memories', size: 'medium', tags: ['memories'], features: ['Photos/docs', 'Notes', 'Categories', 'Timeline', 'Tags', 'Search'] },
  { id: 'wiki', name: 'Personal Wiki', icon: FaBook, category: 'personal-life', description: 'Personal knowledge', size: 'large', tags: ['wiki'], features: ['Pages', 'Links', 'Categories', 'Search', 'Templates', 'Export'] },

  // HEALTH & FITNESS (15)
  { id: 'workout', name: 'Workout Logger', icon: FaDumbbell, category: 'health-fitness', description: 'Track workouts', size: 'large', tags: ['fitness'], features: ['Exercise library', 'Sets/reps', 'PRs', 'Charts', 'Timer'] },
  { id: 'meals', name: 'Meal Planner', icon: FaUtensils, category: 'health-fitness', description: 'Plan meals', size: 'large', tags: ['nutrition'], features: ['Planner', 'Recipes', 'Macros', 'Shopping list'] },
  { id: 'water', name: 'Water Tracker', icon: FaGlassMartini, category: 'health-fitness', description: 'Track hydration', size: 'small', tags: ['hydration'], features: ['Goals', 'Quick log', 'Reminders', 'History'] },
  { id: 'calories', name: 'Calorie Counter', icon: FaAppleAlt, category: 'health-fitness', description: 'Count calories', size: 'medium', tags: ['calories'], features: ['Food database', 'Scanning', 'Logging', 'Totals', 'Goals', 'History'] },
  { id: 'macros', name: 'Macro Tracker', icon: FaCarrot, category: 'health-fitness', description: 'Track macros', size: 'medium', tags: ['macros'], features: ['Protein/carbs/fat', 'Goals', 'Logging', 'Charts', 'Breakdown'] },
  { id: 'weight', name: 'Weight Tracker', icon: FaWeight, category: 'health-fitness', description: 'Track weight', size: 'medium', tags: ['weight'], features: ['Weigh-ins', 'Trends', 'Goals', 'Measurements', 'Photos'] },
  { id: 'sleep', name: 'Sleep Tracker', icon: FaBed, category: 'health-fitness', description: 'Track sleep', size: 'medium', tags: ['sleep'], features: ['Duration', 'Quality', 'Trends', 'Goals', 'Notes', 'Charts'] },
  { id: 'steps', name: 'Step Counter', icon: FaWalking, category: 'health-fitness', description: 'Count steps', size: 'small', tags: ['steps'], features: ['Goal', 'Logging', 'Distance', 'Calories', 'History', 'Trends'] },
  { id: 'hr', name: 'Heart Rate', icon: FaHeartbeat, category: 'health-fitness', description: 'Track HR', size: 'medium', tags: ['heart-rate'], features: ['Logging', 'Resting', 'Zones', 'Trends', 'Alerts'] },
  { id: 'meditation', name: 'Meditation Timer', icon: FaBed, category: 'health-fitness', description: 'Meditation timer', size: 'small', tags: ['meditation'], features: ['Timer', 'Intervals', 'Sounds', 'Log', 'Streaks'] },
  { id: 'running', name: 'Running Log', icon: FaRunning, category: 'health-fitness', description: 'Track runs', size: 'large', tags: ['running'], features: ['Tracking', 'Distance/pace', 'Routes', 'PRs', 'Charts', 'Goals'] },
  { id: 'cycling', name: 'Cycling Tracker', icon: FaBicycle, category: 'health-fitness', description: 'Track cycling', size: 'large', tags: ['cycling'], features: ['Tracking', 'Distance/speed', 'Routes', 'Elevation', 'Charts', 'Goals'] },
  { id: 'swimming', name: 'Swimming Log', icon: FaSwimmer, category: 'health-fitness', description: 'Track swimming', size: 'medium', tags: ['swimming'], features: ['Tracking', 'Laps/distance', 'Strokes', 'Times', 'Progress'] },
  { id: 'strength', name: 'Strength Training', icon: FaDumbbell, category: 'health-fitness', description: 'Strength workouts', size: 'large', tags: ['strength'], features: ['Library', 'Sets/reps', 'Progression', 'Timer', 'PRs', 'Programs'] },
  { id: 'fitness-goals', name: 'Fitness Goals', icon: FaMedal, category: 'health-fitness', description: 'Track fitness goals', size: 'medium', tags: ['goals'], features: ['Goals', 'PRs', 'Achievements', 'Milestones', 'Charts'] },

  // LEARNING (12)
  { id: 'flashcards', name: 'Flashcards', icon: FaGraduationCap, category: 'learning', description: 'Spaced repetition', size: 'medium', tags: ['flashcards'], features: ['Decks', 'Spaced repetition', 'Progress', 'Import/export', 'Stats'] },
  { id: 'study', name: 'Study Planner', icon: FaGraduationCap, category: 'learning', description: 'Plan studies', size: 'large', tags: ['studying'], features: ['Schedule', 'Topics', 'Time', 'Exams', 'Resources'] },
  { id: 'skills', name: 'Skill Tracker', icon: FaBullseye, category: 'learning', description: 'Track skills', size: 'medium', tags: ['skills'], features: ['Skills', 'Levels', 'Resources', 'Practice', 'Certificates'] },
  { id: 'courses', name: 'Course Manager', icon: FaGraduationCap, category: 'learning', description: 'Manage courses', size: 'large', tags: ['courses'], features: ['List', 'Modules', 'Assignments', 'Progress', 'Certs', 'Notes'] },
  { id: 'assignments', name: 'Assignments', icon: FaTasks, category: 'learning', description: 'Track assignments', size: 'medium', tags: ['assignments'], features: ['List', 'Due dates', 'Priority', 'Status', 'Grades', 'Notes'] },
  { id: 'grades', name: 'Grade Calculator', icon: FaCalculator, category: 'learning', description: 'Calculate grades', size: 'small', tags: ['grades'], features: ['GPA calc', 'Weighted', 'What-if', 'Tracking', 'Planning'] },
  { id: 'exam-prep', name: 'Exam Prep', icon: FaCalendar, category: 'learning', description: 'Prepare for exams', size: 'medium', tags: ['exams'], features: ['Schedule', 'Topics', 'Practice', 'Time mgmt', 'Checklists'] },
  { id: 'cornell', name: 'Cornell Notes', icon: FaStickyNote, category: 'learning', description: 'Cornell method', size: 'large', tags: ['notes'], features: ['Cornell format', 'Cues', 'Summary', 'Templates', 'Search', 'Export'] },
  { id: 'concept-map', name: 'Concept Map', icon: FaSitemap, category: 'learning', description: 'Concept mapping', size: 'large', tags: ['mind-map'], features: ['Visual', 'Connections', 'Colors', 'Export', 'Collab'] },
  { id: 'quizzes', name: 'Quiz Generator', icon: FaPoll, category: 'learning', description: 'Create quizzes', size: 'medium', tags: ['quizzes'], features: ['Question types', 'Grading', 'Bank', 'Random', 'Results', 'Export'] },
  { id: 'learning-path', name: 'Learning Path', icon: FaRoute, category: 'learning', description: 'Plan learning', size: 'large', tags: ['learning'], features: ['Creation', 'Milestones', 'Resources', 'Progress', 'Certs', 'Recommendations'] },
  { id: 'study-group', name: 'Study Group', icon: FaUsers, category: 'learning', description: 'Study groups', size: 'medium', tags: ['study'], features: ['Creation', 'Scheduling', 'Resources', 'Discussion', 'Tasks', 'Calendar'] },

  // UTILITIES (15)
  { id: 'password', name: 'Password Gen', icon: FaCog, category: 'utilities', description: 'Generate passwords', size: 'small', tags: ['security'], features: ['Length', 'Options', 'Strength', 'Copy'] },
  { id: 'timer-util', name: 'Timer', icon: FaClock, category: 'utilities', description: 'Timers', size: 'small', tags: ['timer'], features: ['Multiple', 'Stopwatch', 'Laps', 'Alerts'] },
  { id: 'qr', name: 'QR Generator', icon: FaHashtag, category: 'utilities', description: 'Generate QR codes', size: 'small', tags: ['qr'], features: ['URL to QR', 'Text to QR', 'Size', 'Download'] },
  { id: 'text', name: 'Text Tools', icon: FaEdit, category: 'utilities', description: 'Text manipulation', size: 'small', tags: ['text'], features: ['Case converter', 'Word count', 'Chars', 'Trim', 'Find/replace'] },
  { id: 'file-conv', name: 'File Converter', icon: FaFileAlt, category: 'utilities', description: 'Convert files', size: 'small', tags: ['converter'], features: ['Image', 'Document', 'Audio/video', 'Batch'] },
  { id: 'img-compress', name: 'Image Compressor', icon: FaFileImage, category: 'utilities', description: 'Compress images', size: 'small', tags: ['images'], features: ['JPG/PNG', 'Quality', 'Batch', 'Preview', 'Download'] },
  { id: 'hash', name: 'Hash Generator', icon: FaFingerprint, category: 'utilities', description: 'Generate hashes', size: 'small', tags: ['hashing'], features: ['MD5/SHA', 'File hash', 'Text hash', 'Copy'] },
  { id: 'lorem', name: 'Lorem Ipsum', icon: FaFileAlt, category: 'utilities', description: 'Placeholder text', size: 'small', tags: ['lorem'], features: ['Paragraphs', 'Words', 'Sentences', 'Lists', 'Copy'] },
  { id: 'color-util', name: 'Color Picker', icon: FaPalette, category: 'utilities', description: 'Pick colors', size: 'small', tags: ['colors'], features: ['Picker', 'Hex/RGB/HSL', 'Palette', 'Gradients', 'Copy'] },
  { id: 'ascii', name: 'ASCII Art', icon: FaFileAlt, category: 'utilities', description: 'ASCII art', size: 'small', tags: ['ascii'], features: ['Text to ASCII', 'Image to ASCII', 'Fonts', 'Copy'] },
  { id: 'random', name: 'Random Number', icon: FaDice, category: 'utilities', description: 'Random numbers', size: 'small', tags: ['random'], features: ['Range', 'Multiple', 'No duplicates', 'Copy'] },
  { id: 'units', name: 'Unit Converter', icon: FaBalanceScale, category: 'utilities', description: 'Convert units', size: 'small', tags: ['converter'], features: ['Length/mass', 'Temp/pressure', 'Energy', 'Currency', 'Custom'] },
  { id: 'clock', name: 'World Clock', icon: FaGlobeAmericas, category: 'utilities', description: 'Time zones', size: 'medium', tags: ['time'], features: ['Time zones', 'Current', 'Conversions', 'Search', 'Favorites'] },
  { id: 'calc', name: 'Calculator', icon: FaCalculator, category: 'utilities', description: 'Basic calculator', size: 'small', tags: ['calculator'], features: ['Basic ops', 'Memory', 'Percentage', 'History', 'Keyboard'] },
  { id: 'countdown', name: 'Countdown', icon: FaClock, category: 'utilities', description: 'Event countdown', size: 'small', tags: ['countdown'], features: ['Multiple', 'Custom events', 'Alerts', 'Share', 'Remaining'] },
];

export const ACCENT_COLORS = ['#00f0ff','#ff006e','#8b5cf6','#10b981','#f59e0b','#ec4899','#06b6d4','#84cc16','#6366f1','#f97316'];

export const SPACE_TEMPLATES = [
  { id: 'trading-desk', name: 'Trading Desk', icon: FaChartLine, description: 'Trading workspace', type: 'finance', accentColor: '#10b981', definition: 'Trading command center', widgets: ['trading-terminal', 'market-scanner', 'portfolio-manager', 'econ-calendar', 'crypto-tracker', 'risk-calc'] },
  { id: 'enterprise', name: 'Enterprise Ops', icon: FaBuilding, description: 'Business ops', type: 'enterprise', accentColor: '#6366f1', definition: 'Operations hub', widgets: ['crm', 'ppm', 'workflow', 'helpdesk', 'bi', 'dms'] },
  { id: 'supply-chain', name: 'Supply Chain', icon: FaTruck, description: 'Supply chain', type: 'operations', accentColor: '#f59e0b', definition: 'SC ops', widgets: ['inventory', 'procurement', 'warehouse', 'shipping', 'demand', 'production'] },
  { id: 'marketing', name: 'Marketing Suite', icon: FaBullhorn, description: 'Marketing', type: 'marketing', accentColor: '#ec4899', definition: 'Marketing center', widgets: ['marketing-auto', 'social', 'content', 'seo', 'ads', 'feedback'] },
  { id: 'hr', name: 'HR Platform', icon: FaUserFriends, description: 'People mgmt', type: 'hr', accentColor: '#06b6d4', definition: 'People & culture', widgets: ['hris', 'ats', 'time', 'performance', 'lms', 'engagement'] },
  { id: 'creative', name: 'Creative Studio', icon: FaPalette, description: 'Creative work', type: 'creative', accentColor: '#8b5cf6', definition: 'Creative projects', widgets: ['graphics', 'video', 'photo', 'ui-ux', 'brand', 'dam'] },
  { id: 'developer', name: 'Developer Hub', icon: FaCode, description: 'Development', type: 'work', accentColor: '#8b5cf6', definition: 'Dev projects', widgets: ['snippets', 'api', 'git', 'db-query', 'markdown', 'json'] },
  { id: 'health', name: 'Health', icon: FaDumbbell, description: 'Health tracking', type: 'personal', accentColor: '#10b981', definition: 'Health journey', widgets: ['workout', 'meals', 'water', 'sleep', 'habits', 'journal'] },
  { id: 'student', name: 'Student', icon: FaGraduationCap, description: 'Academic', type: 'educational', accentColor: '#8b5cf6', definition: 'Study space', widgets: ['study', 'flashcards', 'notes', 'calendar', 'assignments', 'goals'] },
  { id: 'blank', name: 'Blank Canvas', icon: FaFolder, description: 'Start fresh', type: 'personal', accentColor: '#00f0ff', definition: 'Define your space...', widgets: [] }
];

export const getWidget = (widgetId) => WIDGET_REGISTRY.find(w => w.id === widgetId);
export const getWidgetsByCategory = (category) => category === 'all' ? WIDGET_REGISTRY : WIDGET_REGISTRY.filter(w => w.category === category);
export const searchWidgets = (query) => {
  const lowerQuery = query.toLowerCase();
  return WIDGET_REGISTRY.filter(w => w.name.toLowerCase().includes(lowerQuery) || w.description.toLowerCase().includes(lowerQuery) || w.tags?.some(tag => tag.includes(lowerQuery)));
};