# Generated by Django 5.1.7 on 2025-05-29 00:02

import django.db.models.deletion
import src.utils.parser
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="post_media/")),
                ("media_type", models.CharField(default="default", max_length=10)),
                ("order", models.IntegerField(default=0)),
                ("quality", models.CharField(default="720p", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="post.comment",
                    ),
                ),
            ],
            bases=(models.Model, src.utils.parser.TextFieldMixin),
        ),
        migrations.CreateModel(
            name="ThreadPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("Public", "Public"),
                            ("Friends", "Friends Only"),
                            ("Select", "Select People"),
                            ("Exclude", "Exclude People"),
                        ],
                        default="Private",
                        max_length=10,
                    ),
                ),
                (
                    "restriction",
                    models.CharField(
                        choices=[
                            ("SFW", "Safe for Work"),
                            ("NSFW", "Not Safe for Work"),
                        ],
                        default="SFW",
                        max_length=10,
                    ),
                ),
                (
                    "comments_setting",
                    models.CharField(
                        choices=[
                            ("Allow", "Allow Comments"),
                            ("Disable", "Disable Comments"),
                            ("Friends", "Friends Only"),
                            ("Approval", "Require Approval"),
                        ],
                        default="Allow",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("dislikes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(default="")),
                (
                    "poll_question",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("poll_options", models.JSONField(blank=True, default=list)),
                ("poll_expiration_date", models.DateTimeField(blank=True, null=True)),
                (
                    "event_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_disliked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_files",
                    models.ManyToManyField(blank=True, to="post.mediafile"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisualPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("Public", "Public"),
                            ("Friends", "Friends Only"),
                            ("Select", "Select People"),
                            ("Exclude", "Exclude People"),
                        ],
                        default="Private",
                        max_length=10,
                    ),
                ),
                (
                    "restriction",
                    models.CharField(
                        choices=[
                            ("SFW", "Safe for Work"),
                            ("NSFW", "Not Safe for Work"),
                        ],
                        default="SFW",
                        max_length=10,
                    ),
                ),
                (
                    "comments_setting",
                    models.CharField(
                        choices=[
                            ("Allow", "Allow Comments"),
                            ("Disable", "Disable Comments"),
                            ("Friends", "Friends Only"),
                            ("Approval", "Require Approval"),
                        ],
                        default="Allow",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("dislikes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_disliked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s_liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("media_files", models.ManyToManyField(to="post.mediafile")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("upvote", "Upvote"), ("downvote", "Downvote")],
                        max_length=10,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
