# Generated by Django 5.1.7 on 2025-05-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadpost",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_reposts",
                to="post.threadpost",
            ),
        ),
        migrations.AddField(
            model_name="threadpost",
            name="quote_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualpost",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_reposts",
                to="post.visualpost",
            ),
        ),
        migrations.AddField(
            model_name="visualpost",
            name="quote_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
