# Generated by Django 5.1.7 on 2025-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_threadpost_parent_post_threadpost_quote_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadpost",
            name="quote_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visualpost",
            name="quote_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
