# Generated by Django 5.1.7 on 2025-05-29 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("post", "0003_threadpost_quote_text_visualpost_quote_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="threadpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="visualpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("session_id", models.CharField(blank=True, max_length=64, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "user"],
                        name="post_postvi_content_838bf3_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "session_id"],
                        name="post_postvi_content_41551a_idx",
                    ),
                ],
            },
        ),
    ]
