# Generated by Django 5.1.7 on 2025-12-26 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Description/purpose of this space')),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('collaborative', 'Collaborative'), ('educational', 'Educational'), ('creative', 'Creative'), ('finance', 'Finance')], default='personal', max_length=50)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', max_length=20)),
                ('accent_color', models.CharField(default='#00f0ff', help_text='Hex color code', max_length=7)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborating_spaces', to='user.baseuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to='user.baseuser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SpaceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('widget_added', 'Widget Added'), ('widget_removed', 'Widget Removed'), ('widget_configured', 'Widget Configured'), ('collaborator_added', 'Collaborator Added'), ('collaborator_removed', 'Collaborator Removed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='space.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
            options={
                'verbose_name_plural': 'Space activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email of invited user if not yet registered', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_space_invitations', to='user.baseuser')),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_space_invitations', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='space.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(help_text="e.g., 'code-editor', 'portfolio-tracker'", max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-specific configuration')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='space.space')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
