# Generated by Django 5.1.7 on 2025-12-26 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_edit_space', models.BooleanField(default=True)),
                ('can_add_widgets', models.BooleanField(default=True)),
                ('can_remove_widgets', models.BooleanField(default=True)),
                ('can_invite_collaborators', models.BooleanField(default=False)),
                ('can_remove_collaborators', models.BooleanField(default=False)),
                ('can_change_settings', models.BooleanField(default=False)),
                ('can_delete_space', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='spaceactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Space Activities'},
        ),
        migrations.AlterModelOptions(
            name='spacewidget',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spacewidget',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='space',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spaceinvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from inviter'),
        ),
        migrations.AddField(
            model_name='spacewidget',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='accent_color',
            field=models.CharField(default='#00f0ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='space',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_spaces', to='user.baseuser'),
        ),
        migrations.AlterField(
            model_name='space',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom configuration'),
        ),
        migrations.AlterField(
            model_name='space',
            name='definition',
            field=models.TextField(blank=True, help_text='Space purpose/description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spaceactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('widget_added', 'Widget Added'), ('widget_removed', 'Widget Removed'), ('widget_updated', 'Widget Updated'), ('collaborator_added', 'Collaborator Added'), ('collaborator_removed', 'Collaborator Removed'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('privacy_changed', 'Privacy Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='spaceactivity',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details about the action'),
        ),
        migrations.AlterField(
            model_name='spaceactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_activities', to='user.baseuser'),
        ),
        migrations.AlterField(
            model_name='spaceinvitation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='spaceinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='spacewidget',
            name='widget_type',
            field=models.CharField(help_text="e.g., 'code-editor', 'calendar'", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='spaceinvitation',
            unique_together={('space', 'email')},
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['owner', '-updated_at'], name='space_space_owner_i_665185_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['slug'], name='space_space_slug_ee5c47_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceactivity',
            index=models.Index(fields=['space', '-created_at'], name='space_space_space_i_7cc800_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceinvitation',
            index=models.Index(fields=['email', 'status'], name='space_space_email_2844d4_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceinvitation',
            index=models.Index(fields=['invited_user', 'status'], name='space_space_invited_587f96_idx'),
        ),
        migrations.AddIndex(
            model_name='spacewidget',
            index=models.Index(fields=['space', 'order'], name='space_space_space_i_ec0893_idx'),
        ),
        migrations.AddField(
            model_name='spacepermission',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='space.space'),
        ),
        migrations.AddField(
            model_name='spacepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_permissions', to='user.baseuser'),
        ),
        migrations.AddIndex(
            model_name='spacepermission',
            index=models.Index(fields=['space', 'user'], name='space_space_space_i_d0b42b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spacepermission',
            unique_together={('space', 'user')},
        ),
    ]
