# Generated by Django 5.1.7 on 2025-12-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_spacepermission_alter_spaceactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacewidget',
            name='grid_h',
            field=models.IntegerField(default=4, help_text='Grid height in rows'),
        ),
        migrations.AddField(
            model_name='spacewidget',
            name='grid_w',
            field=models.IntegerField(default=4, help_text='Grid width in columns'),
        ),
        migrations.AddField(
            model_name='spacewidget',
            name='grid_x',
            field=models.IntegerField(default=0, help_text='Grid column position'),
        ),
        migrations.AddField(
            model_name='spacewidget',
            name='grid_y',
            field=models.IntegerField(default=0, help_text='Grid row position'),
        ),
        migrations.AddIndex(
            model_name='spacewidget',
            index=models.Index(fields=['space', 'grid_x', 'grid_y'], name='space_space_space_i_82cc26_idx'),
        ),
    ]
