# Generated by Django 5.1.7 on 2025-12-27 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_spacewidget_grid_h_spacewidget_grid_w_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Rich text HTML content')),
                ('mood', models.CharField(blank=True, choices=[('amazing', 'Amazing'), ('good', 'Good'), ('okay', 'Okay'), ('bad', 'Bad'), ('terrible', 'Terrible')], max_length=20, null=True)),
                ('date', models.DateField(help_text='Entry date (can be different from created_at)')),
                ('is_private', models.BooleanField(default=False, help_text='If true, only author can see this entry even in shared space')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='space.space')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='journal_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.baseuser')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='space.journalentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_comments', to='user.baseuser')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='space.journalentry')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='space.journalentrycomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('icon', models.CharField(default='folder', help_text='Icon name/emoji', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_folders', to='user.baseuser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='space.journalfolder')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_folders', to='space.space')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='space.journalfolder'),
        ),
        migrations.CreateModel(
            name='JournalStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_entries', models.IntegerField(default=0)),
                ('entries_this_month', models.IntegerField(default=0)),
                ('entries_this_week', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('avg_entries_per_week', models.FloatField(default=0.0)),
                ('most_common_mood', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_stats', to='space.spacewidget')),
            ],
            options={
                'verbose_name_plural': 'Journal Stats',
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_tags', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tags', to='space.space')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='space.journaltag'),
        ),
        migrations.AddIndex(
            model_name='journalfolder',
            index=models.Index(fields=['space', 'parent'], name='space_journ_space_i_452692_idx'),
        ),
        migrations.AddIndex(
            model_name='journalfolder',
            index=models.Index(fields=['space', 'order'], name='space_journ_space_i_5a2459_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltag',
            index=models.Index(fields=['space', 'name'], name='space_journ_space_i_856296_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaltag',
            unique_together={('space', 'name')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['space', '-date'], name='space_journ_space_i_6c8e27_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['space', 'author', '-date'], name='space_journ_space_i_5f7c83_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['space', 'folder', '-date'], name='space_journ_space_i_64c90c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['space', 'is_archived', '-date'], name='space_journ_space_i_67e5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['author', '-date'], name='space_journ_author__8efd9f_idx'),
        ),
    ]
