# Generated by Django 5.1.7 on 2025-12-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_journalentry_journalattachment_journalentrycomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text HTML content'),
        ),
    ]
