# Generated by Django 5.1.7 on 2025-12-29 22:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_journalentry_content'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='space.space')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='space.spacewidget')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budgets', models.IntegerField(default=0)),
                ('active_budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_budget_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilization_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_stats', to='space.spacewidget')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=25)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('wallet_address', models.CharField(blank=True, max_length=255)),
                ('chain', models.CharField(blank=True, max_length=50)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_holdings', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_holdings', to='space.space')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_holdings', to='space.spacewidget')),
            ],
            options={
                'ordering': ['-market_value', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('icon', models.CharField(default='tag', max_length=50)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget limit for this category', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='space.space')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='space.spacewidget')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/%Y/%m/')),
                ('receipt_url', models.URLField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_reimbursable', models.BooleanField(default=True)),
                ('is_reimbursed', models.BooleanField(default=False)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='space.space')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_expenses', to='user.baseuser')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='space.spacewidget')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='space.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='space.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='space.expensecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_expenses', models.IntegerField(default=0)),
                ('month_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_stats', to='space.spacewidget')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('brokerage', 'Brokerage'), ('401k', '401(k)'), ('ira', 'IRA'), ('roth_ira', 'Roth IRA'), ('hsa', 'HSA'), ('crypto', 'Crypto Wallet'), ('other', 'Other')], max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_accounts', to='user.baseuser')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_accounts', to='space.space')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_accounts', to='space.spacewidget')),
            ],
            options={
                'ordering': ['-current_value', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('bond', 'Bond'), ('crypto', 'Cryptocurrency'), ('option', 'Option'), ('cash', 'Cash'), ('other', 'Other')], default='stock', max_length=50)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='space.portfolioaccount')),
            ],
            options={
                'ordering': ['-market_value', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('total_holdings', models.IntegerField(default=0)),
                ('today_change', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_return', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stats', to='space.spacewidget')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('split', 'Stock Split')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('shares', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='space.portfolioaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_transactions', to='user.baseuser')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='space.portfolioholding')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['space', 'widget', '-start_date'], name='space_budge_space_i_c9e8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status', '-start_date'], name='space_budge_status_01fe32_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoholding',
            index=models.Index(fields=['space', 'widget', '-market_value'], name='space_crypt_space_i_2fcea2_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoholding',
            index=models.Index(fields=['symbol'], name='space_crypt_symbol_d2ea07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('space', 'widget', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['space', 'widget', '-date'], name='space_expen_space_i_46d9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['submitted_by', '-date'], name='space_expen_submitt_50b142_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-date'], name='space_expen_status_c52bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', '-date'], name='space_expen_categor_fd7939_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['budget', 'category'], name='space_budge_budget__de7aef_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['space', 'widget'], name='space_portf_space_i_f61d26_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioaccount',
            index=models.Index(fields=['owner', '-current_value'], name='space_portf_owner_i_c99080_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['account', '-market_value'], name='space_portf_account_8c7c71_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['symbol'], name='space_portf_symbol_df22f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioholding',
            unique_together={('account', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='portfoliotransaction',
            index=models.Index(fields=['account', '-date'], name='space_portf_account_350213_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotransaction',
            index=models.Index(fields=['holding', '-date'], name='space_portf_holding_b4da2d_idx'),
        ),
    ]
