# Generated by Django 5.1.7 on 2025-12-26 00:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('a_pid', models.CharField(db_index=True, max_length=32)),
                ('b_pid', models.CharField(db_index=True, max_length=32)),
                ('a_meta', models.JSONField(blank=True, default=dict)),
                ('b_meta', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_pid', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fourChat.chatsession')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='PingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pid', models.CharField(max_length=32)),
                ('to_pid', models.CharField(blank=True, max_length=32, null=True)),
                ('ticket', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['from_pid'], name='fourChat_pi_from_pi_4b5d42_idx'), models.Index(fields=['ticket'], name='fourChat_pi_ticket_06a176_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fourChat.chatsession')),
            ],
        ),
    ]
