"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

from .config import DJANGO_SECRET_KEY
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

from .config import (
    GOOGLE_CLIENT_ID,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GITHUB_REDIRECT_URI,
    FRONTEND_REDIRECT_URI
)
# === OAuth Configuration ===
OAUTH_CONFIG = {
    "GOOGLE_CLIENT_ID": GOOGLE_CLIENT_ID,
    "GITHUB_CLIENT_ID": GITHUB_CLIENT_ID,
    "GITHUB_CLIENT_SECRET": GITHUB_CLIENT_SECRET,
    "GITHUB_REDIRECT_URI": GITHUB_REDIRECT_URI,
    "FRONTEND_REDIRECT_URI": FRONTEND_REDIRECT_URI,
}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'
# DEBUG = False

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "10.0.0.6",
    "10.0.0.85",
    "4spacez.vercel.app",
    "fourspace-ybgm.onrender.com"
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    'src.user.apps.UserConfig',
    'src.messaging.apps.MessagingConfig',
    'src.post',
    'src.report',
    'src.userSearchHistory',
    'src.utils',
    'src.notifications',
    
    'src.organization',
    'src.community',
    
    'src.space.projects',
    'src.space.library',
    'src.space.repos',
    'src.space.space',
    
    'src.settings',
    'src.central.collection.apps.CollectionConfig',
    
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken', 
    'api',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'src.user.authentication.HandleTokenAuthentication',
        'src.user.authentication.HandleSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  
    ),
}

MIDDLEWARE = [    
    'corsheaders.middleware.CorsMiddleware',
        
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",    
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"
ASGI_APPLICATION = 'api.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use InMemoryChannelLayer if Redis is not needed
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

from .config import DATABASE_CONFIG

DATABASES = {
    'default': DATABASE_CONFIG['default']
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


DATA_UPLOAD_MAX_NUMBER_FILES = 2000


AUTH_USER_MODEL = 'user.AuthUser'
AUTH_PROFILE_MODEL = 'user.BaseUser'



# CORS settings
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://10.0.0.85:3000",
    "http://10.0.0.6:8000",
    "http://10.0.0.6:3000",
    "https://4spacez.vercel.app",
    "https://fourspace-ybgm.onrender.com"
]

# CORS_ALLOW_ALL_ORIGINS = True


# import pymysql

# pymysql.install_as_MySQLdb()



from .config import USE_AZURE_STORAGE

if USE_AZURE_STORAGE:
    DEFAULT_FILE_STORAGE = 'api.storage_backends.AzureMediaStorage'
    AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER = os.getenv("AZURE_MEDIA_CONTAINER", "media")
    AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}"
    MEDIA_URL = f"https://{AZURE_CUSTOM_DOMAIN}/"
else:
    from .config import MEDIA_URL, MEDIA_ROOT

import os
os.environ["IMAGEIO_FFMPEG_EXE"] = '/opt/homebrew/bin/ffmpeg'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))