# Generated by Django 5.1.7 on 2025-06-20 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_calculatorexpression"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatorexpression",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculator_expressions",
                to="user.baseuser",
            ),
        ),
    ]
