# Generated by Django 5.1.7 on 2025-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
