# Generated by Django 5.1.7 on 2025-08-19 20:29

import django.db.models.deletion
import src.messaging.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("personal", "personal"),
                    ("work", "work"),
                    ("family", "family"),
                    ("dating", "dating"),
                    ("travel", "travel"),
                    ("events", "events"),
                    ("wellness", "wellness"),
                ],
                default=src.messaging.models.conversation_mode_default,
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="theme",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Lane",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Main", max_length=40)),
                ("emoji", models.CharField(blank=True, default="", max_length=8)),
                (
                    "color",
                    models.CharField(blank=True, default="#0A84FF", max_length=7),
                ),
                ("rules", models.JSONField(blank=True, default=dict)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanes",
                        to="messaging.conversation",
                    ),
                ),
            ],
            options={
                "unique_together": {("conversation", "title")},
            },
        ),
        migrations.AddField(
            model_name="message",
            name="lane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="messaging.lane",
            ),
        ),
    ]
