# Generated by Django 5.1.7 on 2025-08-20 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_conversation_mode_conversation_theme_lane_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lane",
            unique_together=set(),
        ),
    ]
