# Generated by Django 5.1.7 on 2025-12-26 00:01

import django.db.models.deletion
import django.db.models.functions.text
import src.community.models
import src.community.research.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(help_text='3–21 chars: letters, digits or underscore; case-insensitive uniqueness.', max_length=21)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='General', help_text="Optional category tag for filtering/grouping (e.g., 'tech', 'education')", max_length=100)),
                ('type', models.CharField(blank=True, default='general', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite', 'Invite Only')], default='public', max_length=10)),
                ('allow_custom_tabs', models.BooleanField(default=True)),
                ('restricted_to_org_members', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=src.community.models.community_banner_upload_path)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=src.community.models.community_logo_upload_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to='user.baseuser')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_communities', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_calls', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='community.community')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='community.community')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('instructor', 'Instructor'), ('student', 'Student'), ('employee', 'Employee'), ('member', 'Member')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_made', to='user.baseuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='community.community')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=src.community.research.models.research_file_upload_path)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='community.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_posts', to='user.baseuser')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='community.community')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_replies', to='user.baseuser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.exchangereply')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.exchangepost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=100)),
                ('amount_raised', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investors', models.TextField()),
                ('announced_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='community.community')),
            ],
            options={
                'ordering': ['-announced_on'],
            },
        ),
        migrations.CreateModel(
            name='Preprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=src.community.research.models.research_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprints', to='community.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to=src.community.research.models.research_file_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_publications', to='community.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseuser')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='community.researchpublication')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('founded_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='community.community')),
            ],
            options={
                'ordering': ['-founded_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='uq_community_slug_ci'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='communitypermission',
            unique_together={('community', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='communitytab',
            unique_together={('community', 'key')},
        ),
    ]
