# Generated by Django 5.1.7 on 2025-06-23 23:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
        ("organization", "0001_initial"),
        ("user", "0003_baseuser_professional_tab_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="slug",
            field=models.CharField(
                help_text="3–21 chars: letters, digits or underscore; case-insensitive uniqueness.",
                max_length=21,
            ),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uq_community_slug_ci",
            ),
        ),
    ]
