# Generated by Django 5.1.7 on 2025-06-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_alter_exchangepost_author_exchangereply"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangepost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_posts",
                to="user.baseuser",
            ),
        ),
    ]
