# Generated by Django 5.1.7 on 2025-06-27 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_alter_exchangepost_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangepost",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="exchangereply",
            name="upvotes",
        ),
    ]
