# Generated by Django 5.1.7 on 2025-08-29 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_remove_exchangepost_upvotes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_name", models.CharField(max_length=100)),
                ("amount_raised", models.DecimalField(decimal_places=2, max_digits=12)),
                ("investors", models.TextField()),
                ("announced_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_rounds",
                        to="community.community",
                    ),
                ),
            ],
            options={
                "ordering": ["-announced_on"],
            },
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("founded_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startups",
                        to="community.community",
                    ),
                ),
            ],
            options={
                "ordering": ["-founded_on"],
            },
        ),
    ]
