# Generated by Django 5.1.7 on 2025-06-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "org_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School"),
                            ("company", "Company"),
                            ("research", "Research Lab"),
                            ("startup", "Startup"),
                            ("nonprofit", "Non-Profit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="org_banners/"),
                ),
                (
                    "email_domain",
                    models.CharField(
                        blank=True,
                        help_text="Optional email domain (e.g., 'mit.edu') for restricting user registration.",
                        max_length=100,
                    ),
                ),
                (
                    "require_domain_email",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only users with this domain can join automatically.",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with links like {'twitter': '...', 'linkedin': '...'}",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_created",
                        to="user.baseuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("employee", "Employee"),
                            ("member", "Member"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this user has been approved by the organization admin.",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_invitations",
                        to="user.baseuser",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organization.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.baseuser"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "organization")},
            },
        ),
    ]
